"use client";
import { FormEvent,useEffect,useMemo,useState } from "react";
import Link from "next/link";
import { Armchair,Bell,CalendarClock,CircleDollarSign,FileText,HeartPulse,Home,ListChecks,Menu,RotateCcw,Settings,Store,UsersRound,X } from "lucide-react";
import { demoSeed,type DemoState,type DemoRundown } from "@/lib/demo-data";

type View="home"|"plan"|"money"|"guests"|"vendors"|"seating"|"timeline"|"health"|"alerts"|"vault"|"team"|"settings"|"dayh";
const nav:[View,any,string][]=[
 ["home",Home,"Home"],["plan",ListChecks,"Plan"],["money",CircleDollarSign,"Money"],["guests",UsersRound,"Guests"],
 ["vendors",Store,"Vendors"],["seating",Armchair,"Seating"],["timeline",CalendarClock,"Timeline"],["health",HeartPulse,"Health"],["alerts",Bell,"Alerts"],["vault",FileText,"Vault"],
 ["team",UsersRound,"Team"],["settings",Settings,"Settings"],["dayh",CalendarClock,"Day-H"]
];
const money=(n:number)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const s=(f:FormData,k:string)=>String(f.get(k)||"").trim();
const n=(f:FormData,k:string)=>Math.max(0,Number(f.get(k)||0));
const nextId=(arr:{id:number}[])=>arr.length?Math.max(...arr.map(x=>x.id))+1:1;

export default function Demo(){
 const[data,setData]=useState<DemoState>(demoSeed),[view,setView]=useState<View>("home"),[ready,setReady]=useState(false),[more,setMore]=useState(false);
 useEffect(()=>{const saved=localStorage.getItem("menujukita_demo_v4");if(saved)try{setData(JSON.parse(saved))}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)localStorage.setItem("menujukita_demo_v4",JSON.stringify(data))},[data,ready]);
 const done=data.tasks.filter(t=>t.status==="done").length,progress=data.tasks.length?Math.round(done/data.tasks.length*100):0;
 const paid=data.payments.filter(p=>p.status==="Paid").reduce((x,p)=>x+p.amount,0),committed=data.payments.filter(p=>p.status!=="Paid").reduce((x,p)=>x+p.amount,0);
 const safe=Math.max(0,data.budget-paid-committed-data.reserve),booked=data.vendors.filter(v=>["Booked","Completed"].includes(v.status)).length;
 const attending=data.guests.filter(g=>g.rsvp==="Attending").reduce((x,g)=>x+g.pax,0),waiting=data.guests.filter(g=>["Waiting","Maybe"].includes(g.rsvp)).length,declined=data.guests.filter(g=>g.rsvp==="Declined").length;
 const overdue=data.payments.filter(p=>p.status==="Overdue").length;
 const health=Math.max(35,Math.min(98,Math.round(progress*.35+(booked/Math.max(1,data.vendors.length))*25+Math.min(100,attending/Math.max(1,data.targetGuests)*100)*.18+(safe>0?18:6)-overdue*3)));
 const reset=()=>{localStorage.removeItem("menujukita_demo_v4");setData(demoSeed);setView("home")};
 const go=(v:View)=>{setView(v);setMore(false);window.scrollTo({top:0,behavior:"smooth"})};
 return <div className="demo-studio demo-full">
  <aside className="studio-rail demo-rail"><Link className="studio-logo" href="/">M</Link>{nav.slice(0,7).map(([id,I,label])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><I size={20}/><span>{label}</span></button>)}<div className="rail-spacer"/><button onClick={()=>go("dayh")} className={view==="dayh"?"active":""}><CalendarClock size={20}/><span>Day-H</span></button><button className="rail-more" onClick={()=>setMore(v=>!v)}><Menu size={20}/><span>More</span></button></aside>
  <div className="studio-frame"><header className="studio-topbar demo-top"><div className="studio-title"><small>DEMO PRO · FULL WEDDING SANDBOX</small><strong>{data.couple}</strong><span>{data.days} hari menuju hari kalian · {data.guests.length} guest entries · {data.tasks.length} tasks</span></div><div className="demo-top-actions"><button className="btn btn-sm" onClick={reset}><RotateCcw size={14}/>Reset Demo</button><Link className="btn btn-primary btn-sm" href="/checkout">Beli Rp49.000</Link></div></header>
  <div className="demo-mode-banner"><span><b>Full Interactive Demo</b> · semua tambah/edit/hapus tersimpan lokal di browser.</span><span>Tidak memakai database atau slot lisensi.</span></div>
  <main className="studio-view">{view==="home"&&<DemoHome data={data} progress={progress} health={health} safe={safe} booked={booked} attending={attending} overdue={overdue} go={go}/>}
   {view==="plan"&&<DemoPlan data={data} setData={setData}/>}
   {view==="money"&&<DemoMoney data={data} setData={setData} safe={safe} paid={paid} committed={committed}/>}
   {view==="guests"&&<DemoGuests data={data} setData={setData} attending={attending} waiting={waiting} declined={declined}/>}
   {view==="vendors"&&<DemoVendors data={data} setData={setData}/>}
   {view==="seating"&&<DemoSeating data={data} setData={setData}/>}
   {view==="timeline"&&<DemoTimeline data={data} setData={setData}/>}
   {view==="health"&&<DemoHealth data={data}/>} 
   {view==="alerts"&&<DemoAlerts data={data} go={go}/>} 
   {view==="vault"&&<DemoVault data={data} setData={setData}/>}
   {view==="team"&&<DemoTeam data={data} setData={setData}/>}
   {view==="settings"&&<DemoSettings data={data} setData={setData}/>}
   {view==="dayh"&&<DemoDayH data={data} setData={setData}/>}
  </main></div>
  <nav className="studio-mobile-nav">{nav.slice(0,4).map(([id,I,label])=><button key={id} className={view===id?"active":""} onClick={()=>go(id)}><I size={20}/><small>{label}</small></button>)}<button className={more?"active":""} onClick={()=>setMore(v=>!v)}><Menu size={20}/><small>More</small></button></nav>
  {more&&<><button className="studio-sheet-backdrop" onClick={()=>setMore(false)}/><aside className="studio-more-sheet"><div className="sheet-head"><div><small>DEMO PRO</small><h3>Semua ruang wedding</h3></div><button className="icon-button" onClick={()=>setMore(false)}><X size={18}/></button></div><div className="more-grid">{nav.slice(4).map(([id,I,label])=><button key={id} onClick={()=>go(id)} className={view===id?"active":""}><I size={19}/><span>{label}</span></button>)}</div></aside></>}
 </div>
}

function DemoHome({data,progress,health,safe,booked,attending,overdue,go}:{data:DemoState;progress:number;health:number;safe:number;booked:number;attending:number;overdue:number;go:(v:View)=>void}){
 const priority=data.tasks.filter(t=>t.status!=="done").sort((a,b)=>({critical:0,high:1,medium:2,low:3}[a.priority]-({critical:0,high:1,medium:2,low:3}[b.priority]))).slice(0,5);
 return <section className="studio-home">
  <div className="home-editorial couple-cover-hero demo-cover-hero"><div><span className="micro-label">FULL DEMO WEDDING</span><h1 className="serif">{data.couple}<em> · demo</em></h1><p><strong>{data.days} hari</strong> menuju {data.date}. Data ini sengaja padat agar seluruh alur wedding planner dapat dicoba.</p></div><div className="health-orbit" style={{"--health":health} as any}><div><b>{health}</b><span>Wedding Health</span><small>{health>=80?"On Track":health>=65?"Needs Attention":"At Risk"}</small></div></div></div>
  <div className="attention-layout"><section className="attention-card"><div className="section-kicker">WHAT NEEDS YOUR ATTENTION</div><div className="attention-list">{priority.map((t,i)=><button className="attention-row" key={t.id} onClick={()=>go("plan")}><span className="attention-index">{String(i+1).padStart(2,"0")}</span><span className="attention-copy"><b>{t.title}</b><small>{t.phase} · {t.due}</small></span><span className="attention-kind">{t.category}</span></button>)}</div></section><aside className="today-stack"><div className="studio-stat safe-focus"><small>SAFE TO SPEND</small><strong>{money(safe)}</strong><span>setelah paid, committed & buffer</span></div><div className="studio-stat"><small>PROGRESS</small><strong>{progress}%</strong><div className="studio-progress"><span style={{width:progress+"%"}}/></div><span>{booked}/{data.vendors.length} vendor secured · {attending} pax confirmed</span></div><div className="studio-stat"><small>PAYMENT ALERT</small><strong>{overdue}</strong><span>pembayaran overdue</span></div></aside></div>
  <div className="demo-dashboard-grid"><button onClick={()=>go("plan")}><b>{data.tasks.length}</b><span>Tasks</span></button><button onClick={()=>go("money")}><b>{data.budgetItems.length}</b><span>Budget items</span></button><button onClick={()=>go("guests")}><b>{data.guests.length}</b><span>Guests</span></button><button onClick={()=>go("vendors")}><b>{data.vendors.length}</b><span>Vendors</span></button><button onClick={()=>go("seating")}><b>{data.seating.length}</b><span>Tables</span></button><button onClick={()=>go("timeline")}><b>{data.rundown.length}</b><span>Rundown items</span></button><button onClick={()=>go("vault")}><b>{data.documents.length}</b><span>Documents</span></button><button onClick={()=>go("team")}><b>{data.members.length}</b><span>Team / PIC</span></button></div>
 </section>
}

function DemoPlan({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 const phases=Array.from(new Set(data.tasks.map(t=>t.phase)));
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),title=s(f,"title");if(!title)return;setData(d=>({...d,tasks:[...d.tasks,{id:nextId(d.tasks),title,phase:s(f,"phase")||"Custom",category:s(f,"category")||"General",due:s(f,"due")||"Belum dijadwalkan",status:"todo",priority:(s(f,"priority")||"medium") as any,assignee:s(f,"assignee")||"Belum ada"}]}));e.currentTarget.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,tasks:d.tasks.map(t=>t.id===id?{...t,title:s(f,"title"),phase:s(f,"phase"),category:s(f,"category"),due:s(f,"due"),priority:s(f,"priority") as any,status:s(f,"status") as any,assignee:s(f,"assignee")}:t)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">PLAN · {data.tasks.length} TASKS</span><h2 className="serif">Wedding Journey</h2><p>Contoh checklist profesional dari 12+ bulan, final weeks, Day-H, sampai after wedding. Semua item editable.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah task</span><small>Tambah item baru ke journey</small></summary><form className="editor-form" onSubmit={add}><input className="input span-2" name="title" placeholder="Task baru" required/><input className="input" name="phase" placeholder="Fase" defaultValue="Final Weeks"/><input className="input" name="category" placeholder="Kategori" defaultValue="General"/><input className="input" name="due" placeholder="Deadline" defaultValue="7 hari lagi"/><select className="input" name="priority" defaultValue="medium"><option>low</option><option>medium</option><option>high</option><option>critical</option></select><input className="input span-2" name="assignee" placeholder="PIC" defaultValue="Alya"/><button className="btn btn-primary span-2">Tambah Task</button></form></details>
  <div className="demo-phase-stack">{phases.map(phase=>{const items=data.tasks.filter(t=>t.phase===phase),done=items.filter(t=>t.status==="done").length;return <details className="studio-panel demo-phase" key={phase} open={phase==="Final Weeks"}><summary><div><small>PHASE</small><h3>{phase}</h3></div><span>{done}/{items.length} selesai</span></summary><div className="studio-list">{items.map(t=><details className={"studio-item task-item "+(t.status==="done"?"is-done":"")} key={t.id}><summary><button className={"task-check "+(t.status==="done"?"checked":"")} onClick={e=>{e.preventDefault();setData(d=>({...d,tasks:d.tasks.map(x=>x.id===t.id?{...x,status:x.status==="done"?"todo":"done"}:x)}))}}>{t.status==="done"?"✓":""}</button><div className="item-main"><b>{t.title}</b><span>{t.category} · {t.due} · PIC {t.assignee}</span></div><span className="status-dot">{t.priority}</span></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,t.id)}><input className="input span-2" name="title" defaultValue={t.title}/><input className="input" name="phase" defaultValue={t.phase}/><input className="input" name="category" defaultValue={t.category}/><input className="input" name="due" defaultValue={t.due}/><select className="input" name="priority" defaultValue={t.priority}><option>low</option><option>medium</option><option>high</option><option>critical</option></select><select className="input" name="status" defaultValue={t.status}><option value="todo">todo</option><option value="in_progress">in progress</option><option value="done">done</option></select><input className="input" name="assignee" defaultValue={t.assignee}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,tasks:d.tasks.filter(x=>x.id!==t.id)}))}>Hapus task</button></div></details>)}</div></details>})}</div>
 </section>
}

function DemoMoney({data,setData,safe,paid,committed}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>;safe:number;paid:number;committed:number}){
 function addBudget(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=s(f,"name");if(!name)return;setData(d=>({...d,budgetItems:[...d.budgetItems,{id:nextId(d.budgetItems),name,category:s(f,"category")||"Other",planned:n(f,"planned"),actual:n(f,"actual"),paid:n(f,"paid"),notes:s(f,"notes")}]}));e.currentTarget.reset()}
 function updateBudget(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,budgetItems:d.budgetItems.map(x=>x.id===id?{...x,name:s(f,"name"),category:s(f,"category"),planned:n(f,"planned"),actual:n(f,"actual"),paid:n(f,"paid"),notes:s(f,"notes")}:x)}))}
 function addPayment(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),title=s(f,"title");if(!title)return;setData(d=>({...d,payments:[...d.payments,{id:nextId(d.payments),title,vendor:s(f,"vendor")||"Tanpa vendor",amount:n(f,"amount"),due:s(f,"due")||"Belum dijadwalkan",status:(s(f,"status")||"Upcoming") as any,method:s(f,"method")||"Transfer"}]}));e.currentTarget.reset()}
 function updatePayment(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,payments:d.payments.map(x=>x.id===id?{...x,title:s(f,"title"),vendor:s(f,"vendor"),amount:n(f,"amount"),due:s(f,"due"),status:s(f,"status") as any,method:s(f,"method")}:x)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">MONEY · FULL DEMO</span><h2 className="serif">Wedding Wallet</h2><p>Budget plan, actual cost, vendor payment, buffer, dan Safe to Spend saling terhubung.</p></div></header>
  <div className="wallet-hero"><div><small>SAFE TO SPEND</small><strong>{money(safe)}</strong><span>budget − paid − committed − buffer</span></div><div className="wallet-metrics"><p><small>BUDGET</small><b>{money(data.budget)}</b></p><p><small>PAID</small><b>{money(paid)}</b></p><p><small>COMMITTED</small><b>{money(committed)}</b></p><p><small>BUFFER</small><b>{money(data.reserve)}</b></p></div></div>
  <section className="studio-panel demo-money-settings"><label className="field"><span>Total budget</span><input className="input" type="number" value={data.budget} onChange={e=>setData(d=>({...d,budget:Number(e.target.value)}))}/></label><label className="field"><span>Reserve buffer</span><input className="input" type="number" value={data.reserve} onChange={e=>setData(d=>({...d,reserve:Number(e.target.value)}))}/></label></section>
  <div className="two-column-studio">
   <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>BUDGET PLAN</small><h3>{data.budgetItems.length} alokasi</h3></div></div><details className="inline-composer"><summary>+ Tambah alokasi</summary><form className="editor-form" onSubmit={addBudget}><input className="input span-2" name="name" placeholder="Nama alokasi" required/><input className="input span-2" name="category" placeholder="Kategori"/><input className="input" type="number" name="planned" placeholder="Rencana"/><input className="input" type="number" name="actual" placeholder="Aktual"/><input className="input" type="number" name="paid" placeholder="Terbayar"/><input className="input" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah</button></form></details><div className="studio-list">{data.budgetItems.map(b=><details className="studio-item" key={b.id}><summary><div className="item-main"><b>{b.name}</b><span>{b.category} · paid {money(b.paid)}</span></div><strong>{money(b.actual||b.planned)}</strong></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>updateBudget(e,b.id)}><input className="input span-2" name="name" defaultValue={b.name}/><input className="input span-2" name="category" defaultValue={b.category}/><input className="input" name="planned" type="number" defaultValue={b.planned}/><input className="input" name="actual" type="number" defaultValue={b.actual}/><input className="input" name="paid" type="number" defaultValue={b.paid}/><input className="input" name="notes" defaultValue={b.notes}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,budgetItems:d.budgetItems.filter(x=>x.id!==b.id)}))}>Hapus alokasi</button></div></details>)}</div></section>
   <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>PAYMENTS</small><h3>{data.payments.length} jadwal pembayaran</h3></div></div><details className="inline-composer"><summary>+ Tambah payment</summary><form className="editor-form" onSubmit={addPayment}><input className="input span-2" name="title" placeholder="Nama pembayaran" required/><input className="input span-2" name="vendor" placeholder="Vendor"/><input className="input" type="number" name="amount" placeholder="Nominal"/><input className="input" name="due" placeholder="Deadline"/><select className="input" name="status"><option>Upcoming</option><option>Paid</option><option>Overdue</option></select><input className="input" name="method" placeholder="Metode"/><button className="btn btn-primary span-2">Tambah</button></form></details><div className="studio-list">{data.payments.map(p=><details className="studio-item" key={p.id}><summary><div className="item-main"><b>{p.title}</b><span>{p.vendor} · {p.due}</span></div><div className="item-right"><strong>{money(p.amount)}</strong><span className={"status-dot status-"+p.status.toLowerCase()}>{p.status}</span></div></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>updatePayment(e,p.id)}><input className="input span-2" name="title" defaultValue={p.title}/><input className="input span-2" name="vendor" defaultValue={p.vendor}/><input className="input" type="number" name="amount" defaultValue={p.amount}/><input className="input" name="due" defaultValue={p.due}/><select className="input" name="status" defaultValue={p.status}><option>Upcoming</option><option>Paid</option><option>Overdue</option></select><input className="input" name="method" defaultValue={p.method}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,payments:d.payments.filter(x=>x.id!==p.id)}))}>Hapus pembayaran</button></div></details>)}</div></section>
  </div>
 </section>
}

function DemoGuests({data,setData,attending,waiting,declined}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>;attending:number;waiting:number;declined:number}){
 const[q,setQ]=useState("");const filtered=useMemo(()=>data.guests.filter(g=>[g.name,g.group,g.phone,g.side].join(" ").toLowerCase().includes(q.toLowerCase())),[data.guests,q]);
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=s(f,"name");if(!name)return;setData(d=>({...d,guests:[{id:nextId(d.guests),name,group:s(f,"group")||"Other",side:(s(f,"side")||"Bersama") as any,phone:s(f,"phone"),pax:Math.max(1,n(f,"pax")||1),rsvp:(s(f,"rsvp")||"Waiting") as any,vip:f.get("vip")==="on",dietary:s(f,"dietary"),tableId:null},...d.guests]}));e.currentTarget.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,guests:d.guests.map(g=>g.id===id?{...g,name:s(f,"name"),group:s(f,"group"),side:s(f,"side") as any,phone:s(f,"phone"),pax:Math.max(1,n(f,"pax")||1),rsvp:s(f,"rsvp") as any,vip:f.get("vip")==="on",dietary:s(f,"dietary")}:g)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">GUESTS · {data.guests.length} ENTRIES</span><h2 className="serif">Guest Book + RSVP</h2><p>Household, side keluarga, pax, VIP, dietary notes, RSVP, dan seating semuanya bisa diubah.</p></div></header>
  <div className="guest-overview"><div><small>Target</small><b>{data.targetGuests}</b></div><div><small>Confirmed pax</small><b>{attending}</b></div><div><small>Waiting</small><b>{waiting}</b></div><div><small>Declined</small><b>{declined}</b></div></div>
  <div className="demo-guest-toolbar"><input className="input" value={q} onChange={e=>setQ(e.target.value)} placeholder="Cari nama, group, nomor, side..."/><details className="inline-composer"><summary>+ Tambah tamu</summary><form className="editor-form" onSubmit={add}><input className="input span-2" name="name" placeholder="Nama tamu" required/><input className="input" name="group" placeholder="Group"/><select className="input" name="side"><option>Alya</option><option>Raka</option><option>Bersama</option></select><input className="input" name="phone" placeholder="WhatsApp"/><input className="input" type="number" name="pax" min="1" max="20" defaultValue="1"/><select className="input" name="rsvp"><option>Waiting</option><option>Attending</option><option>Maybe</option><option>Declined</option></select><input className="input" name="dietary" placeholder="Dietary notes"/><label className="demo-check"><input type="checkbox" name="vip"/> VIP</label><button className="btn btn-primary span-2">Tambah</button></form></details></div>
  <div className="guest-book">{filtered.map(g=><details className="guest-contact-card" key={g.id}><summary><div className="guest-avatar">{g.name.slice(0,1)}</div><div className="item-main"><b>{g.name}{g.vip?" · VIP":""}</b><span>{g.group} · {g.side} · {g.phone}</span></div><div className="guest-status"><span className={"status-dot status-"+g.rsvp.toLowerCase()}>{g.rsvp}</span><b>{g.pax} pax</b></div></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,g.id)}><input className="input span-2" name="name" defaultValue={g.name}/><input className="input" name="group" defaultValue={g.group}/><select className="input" name="side" defaultValue={g.side}><option>Alya</option><option>Raka</option><option>Bersama</option></select><input className="input" name="phone" defaultValue={g.phone}/><input className="input" type="number" name="pax" defaultValue={g.pax}/><select className="input" name="rsvp" defaultValue={g.rsvp}><option>Waiting</option><option>Attending</option><option>Maybe</option><option>Declined</option></select><input className="input span-2" name="dietary" defaultValue={g.dietary} placeholder="Dietary notes"/><label className="demo-check"><input type="checkbox" name="vip" defaultChecked={g.vip}/> VIP</label><button className="btn btn-primary">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,guests:d.guests.filter(x=>x.id!==g.id),seating:d.seating.map(t=>({...t,guestIds:t.guestIds.filter(id=>id!==g.id)}))}))}>Hapus tamu</button></div></details>)}</div>
 </section>
}

function DemoVendors({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=s(f,"name");if(!name)return;setData(d=>({...d,vendors:[...d.vendors,{id:nextId(d.vendors),name,category:s(f,"category")||"Other",status:(s(f,"status")||"Searching") as any,quoted:n(f,"quoted"),agreed:n(f,"agreed"),contact:s(f,"contact"),pic:s(f,"pic"),notes:s(f,"notes")}]}));e.currentTarget.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,vendors:d.vendors.map(v=>v.id===id?{...v,name:s(f,"name"),category:s(f,"category"),status:s(f,"status") as any,quoted:n(f,"quoted"),agreed:n(f,"agreed"),contact:s(f,"contact"),pic:s(f,"pic"),notes:s(f,"notes")}:v)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">VENDORS · {data.vendors.length} PARTNERS</span><h2 className="serif">Wedding Partners</h2><p>Kandidat, quotation, deal, PIC, kontak, notes, dan status vendor semuanya editable.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah vendor</span><small>Searching sampai Completed</small></summary><form className="editor-form" onSubmit={add}><input className="input span-2" name="name" placeholder="Nama vendor" required/><input className="input" name="category" placeholder="Kategori"/><select className="input" name="status"><option>Searching</option><option>Shortlisted</option><option>Negotiating</option><option>Booked</option><option>Completed</option></select><input className="input" name="pic" placeholder="PIC"/><input className="input" name="contact" placeholder="WhatsApp"/><input className="input" type="number" name="quoted" placeholder="Quoted"/><input className="input" type="number" name="agreed" placeholder="Agreed"/><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah Vendor</button></form></details>
  <div className="vendor-studio-grid">{data.vendors.map(v=><details className="vendor-studio-card" key={v.id}><summary><div className="vendor-monogram">{v.name.slice(0,2).toUpperCase()}</div><div className="item-main"><small>{v.category}</small><b>{v.name}</b><span>{v.pic} · {v.contact}</span></div><div className="vendor-price"><strong>{money(v.agreed||v.quoted)}</strong><span className="status-dot">{v.status}</span></div></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,v.id)}><input className="input span-2" name="name" defaultValue={v.name}/><input className="input" name="category" defaultValue={v.category}/><select className="input" name="status" defaultValue={v.status}><option>Searching</option><option>Shortlisted</option><option>Negotiating</option><option>Booked</option><option>Completed</option></select><input className="input" name="pic" defaultValue={v.pic}/><input className="input" name="contact" defaultValue={v.contact}/><input className="input" type="number" name="quoted" defaultValue={v.quoted}/><input className="input" type="number" name="agreed" defaultValue={v.agreed}/><textarea className="input span-2" name="notes" defaultValue={v.notes}/><button className="btn btn-primary span-2">Simpan Vendor</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,vendors:d.vendors.filter(x=>x.id!==v.id)}))}>Hapus vendor</button></div></details>)}</div>
 </section>
}

function DemoSeating({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=s(f,"name");if(!name)return;setData(d=>({...d,seating:[...d.seating,{id:nextId(d.seating),name,capacity:Math.max(1,n(f,"capacity")||8),zone:s(f,"zone")||"General",guestIds:[]}]}));e.currentTarget.reset()}
 function updateTable(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,seating:d.seating.map(t=>t.id===id?{...t,name:s(f,"name"),capacity:Math.max(1,n(f,"capacity")),zone:s(f,"zone")}:t)}))}
 function assign(e:FormEvent<HTMLFormElement>,tableId:number){e.preventDefault();const f=new FormData(e.currentTarget),guestId=Number(f.get("guest_id")||0);if(!guestId)return;setData(d=>({...d,guests:d.guests.map(g=>g.id===guestId?{...g,tableId}:g),seating:d.seating.map(t=>({...t,guestIds:t.id===tableId?Array.from(new Set([...t.guestIds,guestId])):t.guestIds.filter(x=>x!==guestId)}))}))}
 function remove(tableId:number,guestId:number){setData(d=>({...d,guests:d.guests.map(g=>g.id===guestId?{...g,tableId:null}:g),seating:d.seating.map(t=>t.id===tableId?{...t,guestIds:t.guestIds.filter(x=>x!==guestId)}:t)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">SEATING · {data.seating.length} TABLES</span><h2 className="serif">Visual Seating</h2><p>Meja, kapasitas, zone, assignment, pindah, dan keluarkan tamu dapat dicoba langsung.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah meja</span><small>Buat table / zone baru</small></summary><form className="editor-form" onSubmit={add}><input className="input span-2" name="name" placeholder="Nama meja" required/><input className="input" type="number" name="capacity" defaultValue="8"/><input className="input" name="zone" placeholder="Zone" defaultValue="General"/><button className="btn btn-primary span-2">Tambah Meja</button></form></details>
  <div className="visual-seating-grid">{data.seating.map(t=>{const guestRows=t.guestIds.map(id=>data.guests.find(g=>g.id===id)).filter(Boolean) as any[],occupied=guestRows.reduce((x,g)=>x+Number(g.pax||1),0);return <details className="visual-table" key={t.id}><summary><div className="table-orbit"><div><Armchair size={20}/><b>{occupied}/{t.capacity}</b></div></div><div className="item-main"><small>{t.zone}</small><b>{t.name}</b><span>{Math.max(0,t.capacity-occupied)} seat tersisa</span></div></summary><div className="table-detail"><div className="seat-chips">{guestRows.map(g=><button key={g.id} onClick={()=>remove(t.id,g.id)} title="Keluarkan dari meja"><span>{g.name}</span><small>{g.pax} pax ×</small></button>)}</div><form className="seat-assist" onSubmit={e=>assign(e,t.id)}><select className="input" name="guest_id" required defaultValue=""><option value="" disabled>Pilih tamu...</option>{data.guests.filter(g=>g.rsvp!=="Declined").map(g=><option key={g.id} value={g.id}>{g.name} · {g.pax} pax</option>)}</select><button className="btn btn-primary">Tempatkan</button></form><form className="editor-form compact-editor" onSubmit={e=>updateTable(e,t.id)}><input className="input" name="name" defaultValue={t.name}/><input className="input" type="number" name="capacity" defaultValue={t.capacity}/><input className="input span-2" name="zone" defaultValue={t.zone}/><button className="btn span-2">Simpan meja</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,guests:d.guests.map(g=>g.tableId===t.id?{...g,tableId:null}:g),seating:d.seating.filter(x=>x.id!==t.id)}))}>Hapus meja</button></div></details>})}</div>
 </section>
}

function DemoTimeline({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),activity=s(f,"activity");if(!activity)return;setData(d=>({...d,rundown:[...d.rundown,{id:nextId(d.rundown),time:s(f,"time")||"12:00",activity,location:s(f,"location"),pic:s(f,"pic"),vendor:s(f,"vendor"),status:"upcoming" as DemoRundown["status"],notes:s(f,"notes")}].sort((a,b)=>a.time.localeCompare(b.time))}));e.currentTarget.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,rundown:d.rundown.map(r=>r.id===id?{...r,time:s(f,"time"),activity:s(f,"activity"),location:s(f,"location"),pic:s(f,"pic"),vendor:s(f,"vendor"),status:s(f,"status") as any,notes:s(f,"notes")}:r).sort((a,b)=>a.time.localeCompare(b.time))}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">TIMELINE · {data.rundown.length} ITEMS</span><h2 className="serif">Master Rundown</h2><p>Contoh rundown detail dari wake-up call sampai wrap. Semua agenda bisa ditambah, edit, hapus, atau diubah status.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah agenda</span><small>Time, PIC, vendor, lokasi</small></summary><form className="editor-form" onSubmit={add}><input className="input" type="time" name="time" required/><input className="input" name="activity" placeholder="Agenda" required/><input className="input" name="location" placeholder="Lokasi"/><input className="input" name="pic" placeholder="PIC"/><input className="input" name="vendor" placeholder="Vendor"/><input className="input" name="notes" placeholder="Notes"/><button className="btn btn-primary span-2">Tambah Agenda</button></form></details>
  <div className="timeline-list demo-master-timeline">{data.rundown.map(r=><details className={"timeline-item "+(r.status==="next"?"active":"")} key={r.id}><summary><time>{r.time}</time><div className="item-main"><b>{r.activity}</b><span>{r.location} · PIC {r.pic} · {r.vendor}</span></div><span className="status-dot">{r.status}</span></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,r.id)}><input className="input" type="time" name="time" defaultValue={r.time}/><input className="input" name="activity" defaultValue={r.activity}/><input className="input" name="location" defaultValue={r.location}/><input className="input" name="pic" defaultValue={r.pic}/><input className="input" name="vendor" defaultValue={r.vendor}/><select className="input" name="status" defaultValue={r.status}><option value="done">done</option><option value="next">next</option><option value="upcoming">upcoming</option></select><textarea className="input span-2" name="notes" defaultValue={r.notes}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,rundown:d.rundown.filter(x=>x.id!==r.id)}))}>Hapus agenda</button></div></details>)}</div>
 </section>
}

function DemoVault({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const form=e.currentTarget,f=new FormData(form),file=(form.elements.namedItem("file") as HTMLInputElement)?.files?.[0],name=file?.name||s(f,"name");if(!name)return;const size=file?`${Math.max(1,Math.round(file.size/1024))} KB`:s(f,"size")||"250 KB";setData(d=>({...d,documents:[...d.documents,{id:nextId(d.documents),name,category:s(f,"category")||"Other",size,notes:s(f,"notes")}]}));form.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,documents:d.documents.map(x=>x.id===id?{...x,name:s(f,"name"),category:s(f,"category"),size:s(f,"size"),notes:s(f,"notes")}:x)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">VAULT · {data.documents.length} DOCUMENTS</span><h2 className="serif">Private Wedding Vault</h2><p>Di Demo, file tidak dikirim ke server. Nama dan metadata file tetap bisa dicoba seperti alur sebenarnya.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah dokumen demo</span><small>Local metadata only</small></summary><form className="editor-form" onSubmit={add}><input className="input span-2" type="file" name="file"/><input className="input span-2" name="name" placeholder="Atau ketik nama file"/><input className="input" name="category" placeholder="Category" defaultValue="Contract"/><input className="input" name="size" placeholder="Size" defaultValue="250 KB"/><textarea className="input span-2" name="notes" placeholder="Notes"/><button className="btn btn-primary span-2">Tambah ke Vault</button></form></details>
  <div className="vault-grid">{data.documents.map(d=><details className="vault-file" key={d.id}><summary><FileText size={20}/><div className="item-main"><b>{d.name}</b><span>{d.category} · {d.size}</span></div></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,d.id)}><input className="input span-2" name="name" defaultValue={d.name}/><input className="input" name="category" defaultValue={d.category}/><input className="input" name="size" defaultValue={d.size}/><textarea className="input span-2" name="notes" defaultValue={d.notes}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(x=>({...x,documents:x.documents.filter(v=>v.id!==d.id)}))}>Hapus dokumen</button></div></details>)}</div>
 </section>
}

function DemoTeam({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 function add(e:FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),name=s(f,"name");if(!name)return;setData(d=>({...d,members:[...d.members,{id:nextId(d.members),name,role:s(f,"role"),access:s(f,"access"),phone:s(f,"phone")}]}));e.currentTarget.reset()}
 function update(e:FormEvent<HTMLFormElement>,id:number){e.preventDefault();const f=new FormData(e.currentTarget);setData(d=>({...d,members:d.members.map(m=>m.id===id?{...m,name:s(f,"name"),role:s(f,"role"),access:s(f,"access"),phone:s(f,"phone")}:m)}))}
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">TEAM · {data.members.length} PEOPLE</span><h2 className="serif">Wedding Team & PIC</h2><p>Pasangan, WO, keluarga, bridesmaid, groomsman, sampai transport PIC dapat dikelola.</p></div></header>
  <details className="composer-card"><summary><span>+ Tambah anggota</span><small>Demo permission metadata</small></summary><form className="editor-form" onSubmit={add}><input className="input span-2" name="name" placeholder="Nama" required/><input className="input" name="role" placeholder="Role"/><input className="input" name="phone" placeholder="Phone"/><input className="input span-2" name="access" placeholder="Access"/><button className="btn btn-primary span-2">Tambah</button></form></details>
  <div className="demo-team-grid">{data.members.map(m=><details className="studio-panel" key={m.id}><summary><div className="guest-avatar">{m.name.slice(0,1)}</div><div className="item-main"><b>{m.name}</b><span>{m.role} · {m.phone}</span></div></summary><div className="item-editor"><form className="editor-form" onSubmit={e=>update(e,m.id)}><input className="input span-2" name="name" defaultValue={m.name}/><input className="input" name="role" defaultValue={m.role}/><input className="input" name="phone" defaultValue={m.phone}/><input className="input span-2" name="access" defaultValue={m.access}/><button className="btn btn-primary span-2">Simpan</button></form><button className="text-danger" onClick={()=>setData(d=>({...d,members:d.members.filter(x=>x.id!==m.id)}))}>Hapus anggota</button></div></details>)}</div>
 </section>
}

function DemoSettings({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 const[draft,setDraft]=useState(data);
 useEffect(()=>setDraft(data),[data.couple,data.date,data.city,data.details,data.targetGuests]);
 return <section className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">WEDDING SETTINGS</span><h2 className="serif">Wedding Profile</h2><p>Identitas wedding, venue, style, planner, target tamu, dan emergency contact semuanya bisa diubah di demo.</p></div></header>
  <section className="cover-settings-card"><div className="settings-cover-preview demo-settings-cover"><div><small>WEDDING COVER</small><strong>{draft.couple}</strong><span>{draft.details.theme}</span></div></div><form className="cover-settings-copy demo-settings-form" onSubmit={e=>{e.preventDefault();setData(draft)}}><label className="field"><span>Nama pasangan</span><input className="input" value={draft.couple} onChange={e=>setDraft(x=>({...x,couple:e.target.value}))}/></label><div className="split"><label className="field"><span>Tanggal</span><input className="input" value={draft.date} onChange={e=>setDraft(x=>({...x,date:e.target.value}))}/></label><label className="field"><span>Kota</span><input className="input" value={draft.city} onChange={e=>setDraft(x=>({...x,city:e.target.value}))}/></label></div><div className="split"><label className="field"><span>Target tamu</span><input className="input" type="number" value={draft.targetGuests} onChange={e=>setDraft(x=>({...x,targetGuests:Number(e.target.value)}))}/></label><label className="field"><span>Venue</span><input className="input" value={draft.details.venue} onChange={e=>setDraft(x=>({...x,details:{...x.details,venue:e.target.value}}))}/></label></div><label className="field"><span>Theme</span><input className="input" value={draft.details.theme} onChange={e=>setDraft(x=>({...x,details:{...x.details,theme:e.target.value}}))}/></label><div className="split"><label className="field"><span>Ceremony</span><input className="input" value={draft.details.ceremony} onChange={e=>setDraft(x=>({...x,details:{...x.details,ceremony:e.target.value}}))}/></label><label className="field"><span>Reception</span><input className="input" value={draft.details.reception} onChange={e=>setDraft(x=>({...x,details:{...x.details,reception:e.target.value}}))}/></label></div><div className="split"><label className="field"><span>Dress code</span><input className="input" value={draft.details.dressCode} onChange={e=>setDraft(x=>({...x,details:{...x.details,dressCode:e.target.value}}))}/></label><label className="field"><span>Hashtag</span><input className="input" value={draft.details.hashtag} onChange={e=>setDraft(x=>({...x,details:{...x.details,hashtag:e.target.value}}))}/></label></div><label className="field"><span>Planner / WO</span><input className="input" value={draft.details.planner} onChange={e=>setDraft(x=>({...x,details:{...x.details,planner:e.target.value}}))}/></label><label className="field"><span>Emergency Contact</span><input className="input" value={draft.details.emergencyContact} onChange={e=>setDraft(x=>({...x,details:{...x.details,emergencyContact:e.target.value}}))}/></label><button className="btn btn-primary">Simpan Wedding Profile</button></form></section>
 </section>
}

function DemoDayH({data,setData}:{data:DemoState;setData:React.Dispatch<React.SetStateAction<DemoState>>}){
 const current=data.rundown.find(r=>r.status==="next")||data.rundown.find(r=>r.status==="upcoming")||data.rundown[0],idx=data.rundown.findIndex(r=>r.id===current?.id),next=data.rundown[idx+1];
 const setCurrent=(id:number)=>setData(d=>({...d,rundown:d.rundown.map(r=>({...r,status:r.id===id?"next":r.status==="next"?"upcoming":r.status}))}));
 return <section className="demo-dayh-local"><div className="dayh-focus-grid"><article className="dayh-current"><span className="dayh-label">NOW</span><div className="dayh-clock">{current?.time}</div><h1>{current?.activity}</h1><p>{current?.location} · PIC {current?.pic}</p></article><article className="dayh-next"><span className="dayh-label">NEXT</span><b>{next?.time||"--:--"}</b><h2>{next?.activity||"Rundown selesai"}</h2><p>{next?.location}</p></article></div><section className="dayh-list-card"><div className="dayh-section-title"><CalendarClock size={18}/><div><h3>Day-H Mission Control</h3><small>{data.details.emergencyContact}</small></div></div>{data.rundown.map(r=><div className={"dayh-row "+(r.id===current?.id?"active":"")} key={r.id}><time>{r.time}</time><div><b>{r.activity}</b><span>{r.location} · {r.vendor}</span></div><div className="demo-dayh-actions"><button onClick={()=>setData(d=>({...d,rundown:d.rundown.map(x=>x.id===r.id?{...x,status:"done"}:x)}))}>Done</button><button onClick={()=>setCurrent(r.id)}>Now</button></div></div>)}</section></section>
}
