"use server";
import crypto from "node:crypto";
import { redirect } from "next/navigation";
import { sql } from "@/lib/db";
import { getLicenseSession,logAccess } from "@/lib/session";
const slugify=(v:string)=>v.toLowerCase().replace(/[^a-z0-9]+/g,"-").replace(/^-|-$/g,"").slice(0,45);
const iso=(d:Date)=>d.toISOString().slice(0,10);
const minusDays=(base:string,days:number)=>{const d=new Date(base+"T12:00:00Z");d.setUTCDate(d.getUTCDate()-days);return iso(d)};
export async function activateWedding(f:FormData){
 const lic:any=await getLicenseSession();if(!lic)redirect("/auth/sign-in");if(lic.wedding_id)redirect("/app");if(lic.status!=="unused")redirect("/license-status");
 const one=String(f.get("one")||"").trim(),two=String(f.get("two")||"").trim(),weddingDate=String(f.get("date")||"");if(!one||!two||!weddingDate)redirect("/onboarding?error=data");
 const budget=Math.max(0,Number(f.get("budget")||0)),guests=Math.max(0,Math.min(5000,Number(f.get("guests")||0))),city=String(f.get("city")||"").trim(),planningStyle=String(f.get("planning_style")||"couple");
 const db=sql(),weddingId=crypto.randomUUID(),actorId=`license:${lic.license_id}`,slug=slugify(one+"-"+two)+"-"+weddingId.slice(0,6);
 const taskTemplates=[["Tentukan estimasi tamu awal","Guest",240,"high"],["Booking venue","Venue",210,"critical"],["Booking catering","Catering",180,"critical"],["Booking fotografer/videografer","Documentation",180,"high"],["Finalisasi konsep dekorasi","Decoration",120,"high"],["Finalisasi busana & fitting","Attire",90,"high"],["Finalisasi desain undangan","Invitation",75,"medium"],["Mulai konfirmasi guest list","Guest",60,"high"],["Finalisasi jumlah tamu ke catering","Guest",21,"critical"],["Konfirmasi seluruh vendor","Vendor",7,"critical"],["Siapkan emergency kit & dokumen penting","Day-H",2,"high"],["Briefing final hari H","Day-H",1,"critical"]] as const;
 const categories=["Venue","Catering","Decoration","Documentation","Attire","Makeup","Wedding Organizer","Entertainment","Invitation","Souvenir","Transportation","Accommodation","Ceremony / Adat","Miscellaneous"];
 const tx:any[]=[db`INSERT INTO weddings(id,owner_auth_user_id,couple_one_name,couple_two_name,wedding_date,city,budget_total,available_funds,reserve_buffer,guest_target,planning_style,slug) VALUES(${weddingId},${actorId},${one},${two},${weddingDate},${city||null},${budget},${budget},${Math.round(budget*0.05)},${guests},${planningStyle},${slug})`,db`INSERT INTO wedding_members(wedding_id,auth_user_id,display_name,role,can_view_budget,status,joined_at) VALUES(${weddingId},${actorId},${one+" & "+two},'owner',true,'active',now())`,db`UPDATE licenses SET status='active',wedding_id=${weddingId},activated_by_auth_user_id=${actorId},activated_at=now(),updated_at=now() WHERE id=${lic.license_id} AND status='unused' AND wedding_id IS NULL`,db`INSERT INTO wedding_events(wedding_id,event_type,name,event_date,start_time,sort_order) VALUES(${weddingId},'ceremony',${String(f.get("ceremony_name")||"Akad / Pemberkatan")},${weddingDate},'09:00',0)`,db`INSERT INTO wedding_events(wedding_id,event_type,name,event_date,start_time,sort_order) VALUES(${weddingId},'reception',${String(f.get("reception_name")||"Resepsi")},${weddingDate},'12:00',1)`,db`INSERT INTO activity_logs(wedding_id,auth_user_id,action,entity_type,entity_id,metadata) VALUES(${weddingId},${actorId},'workspace_activated','wedding',${weddingId},'{"source":"license_onboarding"}'::jsonb)`];
 taskTemplates.forEach(([title,category,days,priority],i)=>tx.push(db`INSERT INTO tasks(wedding_id,title,category,due_date,priority,status,sort_order) VALUES(${weddingId},${title},${category},${minusDays(weddingDate,days)},${priority},'todo',${i})`));categories.forEach((name,i)=>tx.push(db`INSERT INTO budget_categories(wedding_id,name,sort_order) VALUES(${weddingId},${name},${i})`));
 try{await db.transaction(tx,{isolationLevel:"Serializable"});await logAccess({actorType:"license",licenseId:String(lic.license_id),event:"workspace_activated",metadata:{weddingId}})}catch(e){console.error("activation failed",e);redirect("/onboarding?error=activation")}redirect("/app");
}
