"use server";
import crypto from "node:crypto";
import { revalidatePath } from "next/cache";
import { requireBudgetAccess,requireEditor } from "@/lib/workspace";
import { recordActivity } from "@/lib/activity";
const text=(f:FormData,k:string)=>String(f.get(k)||"").trim();
const num=(f:FormData,k:string)=>Math.max(0,Number(f.get(k)||0));
const refresh=()=>revalidatePath("/app");

export async function addTask(f:FormData){
 const{db,wedding,session}=await requireEditor();const title=text(f,"title");if(!title)return;
 const[q]=await db`SELECT count(*)::int count FROM tasks WHERE wedding_id=${wedding.id}`;if(Number(q.count)>=500)throw new Error("Task limit reached");
 const rows=await db`INSERT INTO tasks(wedding_id,title,description,category,due_date,priority,status,assignee_member_id) VALUES(${wedding.id},${title},${text(f,"description")||null},${text(f,"category")||"general"},${text(f,"due_date")||null},${text(f,"priority")||"medium"},'todo',${text(f,"assignee_member_id")||null}) RETURNING id`;
 await recordActivity(db,wedding.id,session.user.id,"task_created","task",String(rows[0]?.id||""),{title});refresh();
}
export async function updateTask(f:FormData){
 const{db,wedding,session}=await requireEditor(),id=text(f,"id"),status=text(f,"status")||"todo",priority=text(f,"priority")||"medium";
 if(!["todo","in_progress","done","skipped"].includes(status)||!["low","medium","high","critical"].includes(priority))return;
 const rows=await db`UPDATE tasks SET title=${text(f,"title")},description=${text(f,"description")||null},category=${text(f,"category")||"general"},due_date=${text(f,"due_date")||null},priority=${priority},status=${status},assignee_member_id=${text(f,"assignee_member_id")||null},completed_at=CASE WHEN ${status}='done' THEN COALESCE(completed_at,now()) ELSE NULL END,updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING title`;
 if(rows[0])await recordActivity(db,wedding.id,session.user.id,"task_updated","task",id,{title:rows[0].title,status});refresh();
}
export async function toggleTask(f:FormData){
 const{db,wedding,session}=await requireEditor(),id=text(f,"id");
 const rows=await db`UPDATE tasks SET status=CASE WHEN status='done' THEN 'todo' ELSE 'done' END,completed_at=CASE WHEN status='done' THEN NULL ELSE now() END,updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING title,status`;
 if(rows[0])await recordActivity(db,wedding.id,session.user.id,"task_toggled","task",id,{title:rows[0].title,status:rows[0].status});refresh();
}
export async function assignTask(f:FormData){
 const{db,wedding,session}=await requireEditor(),id=text(f,"id"),memberId=text(f,"assignee_member_id")||null;
 if(memberId){const ok=await db`SELECT 1 FROM wedding_members WHERE id=${memberId} AND wedding_id=${wedding.id} AND status='active'`;if(!ok[0])return}
 const rows=await db`UPDATE tasks SET assignee_member_id=${memberId},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING title`;
 if(rows[0])await recordActivity(db,wedding.id,session.user.id,"task_assigned","task",id,{memberId});refresh();
}
export async function deleteTask(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id");const rows=await db`DELETE FROM tasks WHERE id=${id} AND wedding_id=${wedding.id} RETURNING title`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"task_deleted","task",id,{title:rows[0].title});refresh()}

export async function addVendor(f:FormData){
 const{db,wedding,session}=await requireEditor(),name=text(f,"name");if(!name)return;const[q]=await db`SELECT count(*)::int count FROM vendors WHERE wedding_id=${wedding.id}`;if(Number(q.count)>=100)throw new Error("Vendor limit reached");
 const rows=await db`INSERT INTO vendors(wedding_id,category,name,pic_name,phone,whatsapp,instagram,email,quoted_price,agreed_price,status,notes) VALUES(${wedding.id},${text(f,"category")||"Other"},${name},${text(f,"pic_name")||null},${text(f,"phone")||null},${text(f,"whatsapp")||null},${text(f,"instagram")||null},${text(f,"email")||null},${num(f,"quoted_price")},${num(f,"agreed_price")},${text(f,"status")||"searching"},${text(f,"notes")||null}) RETURNING id`;
 await recordActivity(db,wedding.id,session.user.id,"vendor_created","vendor",String(rows[0]?.id||""),{name});refresh();
}
export async function updateVendor(f:FormData){
 const{db,wedding,session}=await requireEditor(),id=text(f,"id"),status=text(f,"status");
 if(!["searching","shortlisted","contacted","negotiating","booked","completed","cancelled"].includes(status))return;
 const rows=await db`UPDATE vendors SET name=${text(f,"name")},category=${text(f,"category")||"Other"},pic_name=${text(f,"pic_name")||null},phone=${text(f,"phone")||null},whatsapp=${text(f,"whatsapp")||null},instagram=${text(f,"instagram")||null},email=${text(f,"email")||null},quoted_price=${num(f,"quoted_price")},agreed_price=${num(f,"agreed_price")},status=${status},notes=${text(f,"notes")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING name`;
 if(rows[0])await recordActivity(db,wedding.id,session.user.id,"vendor_updated","vendor",id,{name:rows[0].name,status});refresh();
}
export async function updateVendorStatus(f:FormData){const form=new FormData();form.set("id",text(f,"id"));const{db,wedding}=await requireEditor();const rows=await db`SELECT * FROM vendors WHERE id=${text(f,"id")} AND wedding_id=${wedding.id} LIMIT 1`;if(!rows[0])return;const v:any=rows[0];["name","category","pic_name","phone","whatsapp","instagram","email","quoted_price","agreed_price","notes"].forEach(k=>form.set(k,String(v[k]??"")));form.set("status",text(f,"status"));return updateVendor(form)}
export async function deleteVendor(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id");const rows=await db`DELETE FROM vendors WHERE id=${id} AND wedding_id=${wedding.id} RETURNING name`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"vendor_deleted","vendor",id,{name:rows[0].name});refresh()}

export async function addBudgetItem(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),name=text(f,"name");if(!name)return;const rows=await db`INSERT INTO budget_items(wedding_id,vendor_id,name,planned_amount,actual_amount,paid_amount,due_date,notes) VALUES(${wedding.id},${text(f,"vendor_id")||null},${name},${num(f,"planned_amount")},${num(f,"actual_amount")},0,${text(f,"due_date")||null},${text(f,"notes")||null}) RETURNING id`;await recordActivity(db,wedding.id,session.user.id,"budget_item_created","budget",String(rows[0]?.id||""),{name});refresh()}
export async function updateBudgetItem(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),id=text(f,"id");const rows=await db`UPDATE budget_items SET name=${text(f,"name")},vendor_id=${text(f,"vendor_id")||null},planned_amount=${num(f,"planned_amount")},actual_amount=${num(f,"actual_amount")},paid_amount=0,due_date=${text(f,"due_date")||null},notes=${text(f,"notes")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING name`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"budget_item_updated","budget",id,{name:rows[0].name});refresh()}
export async function deleteBudgetItem(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),id=text(f,"id");const rows=await db`DELETE FROM budget_items WHERE id=${id} AND wedding_id=${wedding.id} RETURNING name`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"budget_item_deleted","budget",id,{name:rows[0].name});refresh()}
export async function updateFunds(f:FormData){const{db,wedding,session}=await requireBudgetAccess();const budgetTotal=num(f,"budget_total"),reserveBuffer=num(f,"reserve_buffer");await db`UPDATE weddings SET budget_total=${budgetTotal},reserve_buffer=${reserveBuffer},updated_at=now() WHERE id=${wedding.id}`;await recordActivity(db,wedding.id,session.user.id,"funds_updated","budget",wedding.id,{budgetTotal,reserveBuffer});refresh()}

export async function addPayment(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),description=text(f,"description");if(!description)return;const amount=Math.max(1,num(f,"amount"));const rows=await db`INSERT INTO payments(wedding_id,vendor_id,budget_item_id,description,amount,due_date,status,payment_method,notes) VALUES(${wedding.id},${text(f,"vendor_id")||null},${text(f,"budget_item_id")||null},${description},${amount},${text(f,"due_date")||null},'upcoming',${text(f,"payment_method")||null},${text(f,"notes")||null}) RETURNING id`;await recordActivity(db,wedding.id,session.user.id,"payment_created","payment",String(rows[0]?.id||""),{description,amount});refresh()}
export async function updatePayment(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),id=text(f,"id"),status=text(f,"status");if(!["upcoming","paid","cancelled"].includes(status))return;const rows=await db`UPDATE payments SET description=${text(f,"description")},vendor_id=${text(f,"vendor_id")||null},budget_item_id=${text(f,"budget_item_id")||null},amount=${Math.max(1,num(f,"amount"))},due_date=${text(f,"due_date")||null},status=${status},paid_at=CASE WHEN ${status}='paid' THEN COALESCE(paid_at,now()) ELSE NULL END,payment_method=${text(f,"payment_method")||null},notes=${text(f,"notes")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING description`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"payment_updated","payment",id,{description:rows[0].description,status});refresh()}
export async function markPaymentPaid(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),id=text(f,"id");const rows=await db`UPDATE payments SET status=CASE WHEN status='paid' THEN 'upcoming' ELSE 'paid' END,paid_at=CASE WHEN status='paid' THEN NULL ELSE now() END,updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING description,status`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"payment_toggled","payment",id,{status:rows[0].status});refresh()}
export async function deletePayment(f:FormData){const{db,wedding,session}=await requireBudgetAccess(),id=text(f,"id");const previous=await db`SELECT 1 FROM wedding_cash_entries WHERE payment_id=${id} AND wedding_id=${wedding.id} LIMIT 1`;if(previous[0])throw new Error("Pembayaran yang pernah dilunasi tidak dapat dihapus dari riwayat. Koreksi statusnya secara jelas.");const rows=await db`DELETE FROM payments WHERE id=${id} AND wedding_id=${wedding.id} AND status<>\'paid\' RETURNING description`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"payment_deleted","payment",id,{description:rows[0].description});refresh()}

export async function addGuest(f:FormData){
 const{db,wedding,session}=await requireEditor(),name=text(f,"name");if(!name)return;const[q]=await db`SELECT count(*)::int count FROM guests WHERE wedding_id=${wedding.id}`;if(Number(q.count)>=1500)throw new Error("Guest limit reached");
 const partyId=crypto.randomUUID(),guestId=crypto.randomUUID(),maxPax=Math.max(1,Math.min(20,num(f,"max_pax")||1));
 await db.transaction([db`INSERT INTO guest_parties(id,wedding_id,party_name,side,group_name,max_pax) VALUES(${partyId},${wedding.id},${name},${text(f,"side")||"other"},${text(f,"group_name")||"Other"},${maxPax})`,db`INSERT INTO guests(id,wedding_id,party_id,name,phone,email,invitation_quantity,expected_pax,rsvp_status,notes) VALUES(${guestId},${wedding.id},${partyId},${name},${text(f,"phone")||null},${text(f,"email")||null},${maxPax},${maxPax},'waiting',${text(f,"notes")||null})`]);
 await recordActivity(db,wedding.id,session.user.id,"guest_created","guest",guestId,{name,maxPax});refresh();
}
export async function updateGuest(f:FormData){
 const{db,wedding,session}=await requireEditor(),id=text(f,"id"),status=text(f,"status");if(!["not_sent","waiting","attending","not_attending","maybe"].includes(status))return;
 const current=await db`SELECT party_id FROM guests WHERE id=${id} AND wedding_id=${wedding.id} LIMIT 1`;if(!current[0])return;
 const pax=Math.max(1,Math.min(20,num(f,"expected_pax")||1)),actual=status==="not_attending"?0:status==="attending"?Math.max(1,Math.min(pax,num(f,"actual_pax")||pax)):null;
 const tx:any[]=[db`UPDATE guests SET name=${text(f,"name")},phone=${text(f,"phone")||null},email=${text(f,"email")||null},expected_pax=${pax},invitation_quantity=${pax},rsvp_status=${status},actual_pax=${actual},dietary_note=${text(f,"dietary_note")||null},notes=${text(f,"notes")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id}`];
 if(current[0].party_id)tx.push(db`UPDATE guest_parties SET party_name=${text(f,"name")},side=${text(f,"side")||"other"},group_name=${text(f,"group_name")||"Other"},max_pax=${pax},notes=${text(f,"notes")||null} WHERE id=${current[0].party_id} AND wedding_id=${wedding.id}`);
 await db.transaction(tx);await recordActivity(db,wedding.id,session.user.id,"guest_updated","guest",id,{status});refresh();
}
export async function importGuests(rows:{name:string;phone?:string;group?:string;pax?:number}[]){const{db,wedding,session}=await requireEditor();const clean=rows.slice(0,500).map(r=>({name:String(r.name||"").trim().slice(0,160),phone:String(r.phone||"").trim().slice(0,40),group:String(r.group||"Other").trim().slice(0,80)||"Other",pax:Math.max(1,Math.min(20,Number(r.pax||1)))})).filter(r=>r.name);if(!clean.length)return{imported:0};const[q]=await db`SELECT count(*)::int count FROM guests WHERE wedding_id=${wedding.id}`;if(Number(q.count)+clean.length>1500)throw new Error("Guest limit reached");const statements:any[]=[];for(const r of clean){const partyId=crypto.randomUUID(),guestId=crypto.randomUUID();statements.push(db`INSERT INTO guest_parties(id,wedding_id,party_name,side,group_name,max_pax) VALUES(${partyId},${wedding.id},${r.name},'other',${r.group},${r.pax})`);statements.push(db`INSERT INTO guests(id,wedding_id,party_id,name,phone,invitation_quantity,expected_pax,rsvp_status) VALUES(${guestId},${wedding.id},${partyId},${r.name},${r.phone||null},${r.pax},${r.pax},'waiting')`)}await db.transaction(statements);await recordActivity(db,wedding.id,session.user.id,"guest_csv_imported","guest",null,{count:clean.length});refresh();return{imported:clean.length}}
export async function setGuestRsvp(f:FormData){const{db,wedding,session}=await requireEditor(),status=text(f,"status"),id=text(f,"id");if(!["waiting","attending","not_attending","maybe"].includes(status))return;const rows=await db`UPDATE guests SET rsvp_status=${status},actual_pax=CASE WHEN ${status}='attending' THEN GREATEST(1,COALESCE(actual_pax,expected_pax,1)) WHEN ${status}='not_attending' THEN 0 ELSE actual_pax END,updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING name`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"guest_status_changed","guest",id,{status});refresh()}
export async function deleteGuest(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id");const rows=await db`SELECT party_id,name FROM guests WHERE id=${id} AND wedding_id=${wedding.id} LIMIT 1`;await db`DELETE FROM guests WHERE id=${id} AND wedding_id=${wedding.id}`;if(rows[0]?.party_id)await db`DELETE FROM guest_parties WHERE id=${rows[0].party_id} AND wedding_id=${wedding.id} AND NOT EXISTS(SELECT 1 FROM guests WHERE party_id=${rows[0].party_id})`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"guest_deleted","guest",id,{name:rows[0].name});refresh()}

export async function addRundownItem(f:FormData){const{db,wedding,session}=await requireEditor(),activity=text(f,"activity"),starts=text(f,"starts_at");if(!activity||!starts)return;const rows=await db`INSERT INTO rundown_items(wedding_id,starts_at,ends_at,activity,location,status,notes,pic_member_id,vendor_id) VALUES(${wedding.id},${starts},${text(f,"ends_at")||null},${activity},${text(f,"location")||null},'upcoming',${text(f,"notes")||null},${text(f,"pic_member_id")||null},${text(f,"vendor_id")||null}) RETURNING id`;await recordActivity(db,wedding.id,session.user.id,"rundown_created","rundown",String(rows[0]?.id||""),{activity});refresh()}
export async function updateRundownItem(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id"),status=text(f,"status");if(!["upcoming","ready","in_progress","done","delayed","cancelled"].includes(status))return;const rows=await db`UPDATE rundown_items SET starts_at=${text(f,"starts_at")},ends_at=${text(f,"ends_at")||null},activity=${text(f,"activity")},location=${text(f,"location")||null},pic_member_id=${text(f,"pic_member_id")||null},vendor_id=${text(f,"vendor_id")||null},status=${status},notes=${text(f,"notes")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING activity`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"rundown_updated","rundown",id,{activity:rows[0].activity,status});refresh()}
export async function assignRundown(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id");const rows=await db`UPDATE rundown_items SET pic_member_id=${text(f,"pic_member_id")||null},vendor_id=${text(f,"vendor_id")||null},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING activity`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"rundown_assigned","rundown",id,{});refresh()}
export async function updateRundownStatus(f:FormData){const{db,wedding,session}=await requireEditor(),status=text(f,"status"),id=text(f,"id");if(!["upcoming","ready","in_progress","done","delayed","cancelled"].includes(status))return;const rows=await db`UPDATE rundown_items SET status=${status},updated_at=now() WHERE id=${id} AND wedding_id=${wedding.id} RETURNING activity`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"rundown_status_changed","rundown",id,{status});refresh()}
export async function deleteRundownItem(f:FormData){const{db,wedding,session}=await requireEditor(),id=text(f,"id");const rows=await db`DELETE FROM rundown_items WHERE id=${id} AND wedding_id=${wedding.id} RETURNING activity`;if(rows[0])await recordActivity(db,wedding.id,session.user.id,"rundown_deleted","rundown",id,{activity:rows[0].activity});refresh()}
