import crypto from "node:crypto";
import { ADMIN_EMAIL,APP_URL,mailShell,sendMail } from "@/lib/email";

export const MENUJUKITA_PRICE=49000;
export const PRODUCT_NAME="MenujuKita";

export const PAYMENT_DEFAULTS=[
 {code:"bri",label:"BRI",type:"bank",accountNo:"518301014886532",accountName:"Muhammad Shadiq Muntashir",merchantId:null,instructions:"Transfer sesuai total order ke rekening BRI ini.",sort:1},
 {code:"mandiri",label:"Mandiri",type:"bank",accountNo:"1510018726163",accountName:"Muhammad Shadiq",merchantId:null,instructions:"Transfer sesuai total order ke rekening Mandiri ini.",sort:2},
 {code:"bsi",label:"BSI",type:"bank",accountNo:"7273584344",accountName:"Muhammad Shadiq Muntashir",merchantId:null,instructions:"Transfer sesuai total order ke rekening Bank Syariah Indonesia ini.",sort:3},
 {code:"bank-sulteng",label:"Bank Sulteng",type:"bank",accountNo:"0010201272944",accountName:"Muhammad Shadiq Muntashir",merchantId:null,instructions:"Transfer sesuai total order ke rekening Bank Sulteng ini.",sort:4},
 {code:"gopay",label:"GoPay",type:"ewallet",accountNo:"082258687238",accountName:"Muhammad Shadiq Muntashir",merchantId:null,instructions:"Kirim sesuai total order ke nomor GoPay ini.",sort:5},
 {code:"qris",label:"QRIS",type:"qris",accountNo:"ID1026601784022",accountName:"TEMAN DIGITAL",merchantId:"ID1026601784022",instructions:"Sebelum melakukan pembayaran, pastikan nama merchant yang muncul adalah TEMAN DIGITAL.",sort:6}
] as const;

let schemaPromise:Promise<void>|null=null;
export function ensureCommerceSchema(db:any){
 if(schemaPromise)return schemaPromise;
 schemaPromise=(async()=>{
  await db`CREATE TABLE IF NOT EXISTS payment_methods(
    code text PRIMARY KEY,
    label text NOT NULL,
    type text NOT NULL CHECK(type IN('bank','ewallet','qris')),
    account_no text,
    account_name text,
    merchant_id text,
    instructions text,
    qr_image_path text,
    sort_order integer NOT NULL DEFAULT 0,
    is_active boolean NOT NULL DEFAULT true,
    updated_at timestamptz NOT NULL DEFAULT now()
  )`;
  await db`CREATE TABLE IF NOT EXISTS orders(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    public_token text NOT NULL UNIQUE,
    order_no text NOT NULL UNIQUE,
    customer_name text NOT NULL,
    customer_email text NOT NULL,
    customer_whatsapp text NOT NULL,
    couple_names text,
    wedding_date date,
    product text NOT NULL DEFAULT 'MenujuKita',
    amount numeric(14,2) NOT NULL DEFAULT 49000,
    payment_method_code text REFERENCES payment_methods(code),
    payment_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending_payment' CHECK(status IN('pending_payment','awaiting_verification','needs_confirmation','payment_rejected','payment_verified','access_sent','completed','cancelled')),
    claimed_at timestamptz,
    verified_at timestamptz,
    access_sent_at timestamptz,
    completed_at timestamptz,
    license_id uuid UNIQUE REFERENCES licenses(id) ON DELETE SET NULL,
    license_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`;
  await db`CREATE TABLE IF NOT EXISTS payment_claims(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    method_code text NOT NULL,
    claimed_at timestamptz NOT NULL DEFAULT now(),
    note text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`;
  await db`CREATE TABLE IF NOT EXISTS email_events(
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
    kind text NOT NULL,
    recipient text NOT NULL,
    status text NOT NULL CHECK(status IN('sent','failed')),
    provider_id text,
    error text,
    created_at timestamptz NOT NULL DEFAULT now()
  )`;
  await db`CREATE TABLE IF NOT EXISTS order_activity(
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
    event text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
  )`;
  await db`CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status,created_at DESC)`;
  await db`CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email)`;
  await db`CREATE INDEX IF NOT EXISTS idx_order_activity_order_created ON order_activity(order_id,created_at)`;
  for(const m of PAYMENT_DEFAULTS){
    await db`INSERT INTO payment_methods(code,label,type,account_no,account_name,merchant_id,instructions,qr_image_path,sort_order,is_active)
      VALUES(${m.code},${m.label},${m.type},${m.accountNo},${m.accountName},${m.merchantId},${m.instructions},${m.code==="qris"?"/qris-teman-digital.svg":null},${m.sort},true)
      ON CONFLICT(code) DO NOTHING`;
  }
 })().catch(err=>{schemaPromise=null;throw err});
 return schemaPromise;
}

export const newOrderNo=()=>{
 const d=new Date(),date=`${d.getFullYear()}${String(d.getMonth()+1).padStart(2,"0")}${String(d.getDate()).padStart(2,"0")}`;
 return `MK-${date}-${crypto.randomBytes(3).toString("hex").toUpperCase()}`;
};
export const newPublicToken=()=>crypto.randomBytes(24).toString("base64url");
const alphabet="ABCDEFGHJKLMNPQRSTUVWXYZ23456789";
const chunk=()=>Array.from({length:4},()=>alphabet[crypto.randomInt(0,alphabet.length)]).join("");
export const newLicenseCode=()=>`MK-${chunk()}-${chunk()}`;
export const newCustomerPin=()=>crypto.randomInt(0,1000000).toString().padStart(6,"0");

export async function addOrderActivity(db:any,orderId:string,event:string,metadata:Record<string,unknown>={}){
 await db`INSERT INTO order_activity(order_id,event,metadata) VALUES(${orderId},${event},${JSON.stringify(metadata)}::jsonb)`;
}
export async function logOrderEmail(db:any,orderId:string,kind:string,recipient:string,fn:()=>Promise<string>){
 try{
  const providerId=await fn();
  await db`INSERT INTO email_events(order_id,kind,recipient,status,provider_id) VALUES(${orderId},${kind},${recipient},'sent',${providerId||null})`;
  await addOrderActivity(db,orderId,"email_sent",{kind,recipient});
  return true;
 }catch(e:any){
  await db`INSERT INTO email_events(order_id,kind,recipient,status,error) VALUES(${orderId},${kind},${recipient},'failed',${String(e?.message||e).slice(0,500)})`;
  await addOrderActivity(db,orderId,"email_failed",{kind,recipient,error:String(e?.message||e).slice(0,180)});
  return false;
 }
}
const money=(n:any)=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(Number(n||0));
const htmlEntities:Record<string,string>={"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;"};
const safe=(value:any)=>String(value??"").replace(/[&<>"]/g,c=>htmlEntities[c]||c);

export async function sendClaimEmails(db:any,order:any){
 const adminSubject=`[MenujuKita] Pembayaran Baru Menunggu Verifikasi — ${order.order_no}`;
 const adminBody=`<p>Halo Admin Teman Digital,</p><p>Ada pembayaran MenujuKita yang perlu diperiksa.</p><p><b>Order ID:</b> ${safe(order.order_no)}<br><b>Nama:</b> ${safe(order.customer_name)}<br><b>Email:</b> ${safe(order.customer_email)}<br><b>WhatsApp:</b> ${safe(order.customer_whatsapp)}<br><b>Produk:</b> MenujuKita<br><b>Nominal:</b> ${money(order.amount)}<br><b>Metode:</b> ${safe(order.payment_label||order.payment_method_code)}<br><b>Status:</b> MENUNGGU VERIFIKASI</p><p>Silakan masuk ke Kanal Admin Teman Digital untuk memastikan pembayaran sudah benar-benar diterima.</p>`;
 const customerSubject="Konfirmasi Pembayaran MenujuKita Kami Terima";
 const customerBody=`<p>Halo ${safe(order.customer_name)},</p><p>Terima kasih sudah melakukan pembayaran untuk <b>MenujuKita</b>.</p><p><b>Order ID:</b> ${safe(order.order_no)}<br><b>Total:</b> ${money(order.amount)}<br><b>Metode Pembayaran:</b> ${safe(order.payment_label||order.payment_method_code)}</p><p><b>Status: Menunggu Verifikasi Pembayaran</b></p><p>Saat ini pembayaran Anda sedang diperiksa oleh Tim Teman Digital. Kode Lisensi dan PIN akan dikirimkan setelah pembayaran berhasil diverifikasi.</p>`;
 await Promise.all([
  logOrderEmail(db,order.id,"payment_claim_admin",ADMIN_EMAIL,()=>sendMail({to:ADMIN_EMAIL,subject:adminSubject,text:`Pembayaran MenujuKita ${order.order_no} menunggu verifikasi. ${order.customer_name}, ${money(order.amount)}, ${order.payment_label||order.payment_method_code}. Buka admin: ${APP_URL}/admin`,html:mailShell("Pembayaran perlu diverifikasi",adminBody,{label:"Buka Kanal Admin",url:`${APP_URL}/admin`}),idempotencyKey:`mk-${order.id}-claim-admin`})),
  logOrderEmail(db,order.id,"payment_claim_customer",order.customer_email,()=>sendMail({to:order.customer_email,subject:customerSubject,text:`Halo ${order.customer_name}. Konfirmasi pembayaran order ${order.order_no} sebesar ${money(order.amount)} sudah kami terima dan sedang diverifikasi. Akses akan dikirim setelah pembayaran terverifikasi.`,html:mailShell("Konfirmasi pembayaran diterima",customerBody,{label:"Lihat Status Pesanan",url:`${APP_URL}/order/${order.public_token}`}),idempotencyKey:`mk-${order.id}-claim-customer`}))
 ]);
}

export async function sendNeedsConfirmationEmail(db:any,order:any){
 const subject="Kami Perlu Konfirmasi Pembayaran MenujuKita Anda";
 const body=`<p>Halo ${safe(order.customer_name)},</p><p>Kami sudah memeriksa transaksi dengan Order ID <b>${safe(order.order_no)}</b>, tetapi pembayaran belum berhasil kami cocokkan.</p><p>Mohon periksa kembali metode pembayaran, nominal, rekening tujuan, dan waktu pembayaran. Jika diperlukan, hubungi Teman Digital dengan mencantumkan Order ID Anda.</p><p>Lisensi tidak akan diterbitkan sampai pembayaran berhasil diverifikasi.</p>`;
 return logOrderEmail(db,order.id,"needs_confirmation",order.customer_email,()=>sendMail({to:order.customer_email,subject,text:`Pembayaran order ${order.order_no} belum berhasil kami cocokkan. Mohon periksa kembali detail pembayaran atau hubungi Teman Digital.`,html:mailShell("Kami perlu konfirmasi pembayaran",body,{label:"Lihat Status Pesanan",url:`${APP_URL}/order/${order.public_token}`}),idempotencyKey:`mk-${order.id}-needs-confirmation-${Date.now()}`}));
}

export async function sendAccessEmail(db:any,order:any,licenseCode:string,pin:string,resend=false){
 const subject="Pembayaran Berhasil — Akses MenujuKita Anda Sudah Siap";
 const body=`<p>Halo ${safe(order.customer_name)},</p><p>Pembayaran Anda telah berhasil kami verifikasi. Terima kasih telah membeli <b>MenujuKita</b> dari Teman Digital.</p><p><b>Order ID:</b> ${safe(order.order_no)}<br><b>Total:</b> ${money(order.amount)}<br><b>Status Pembayaran:</b> Berhasil</p><div style="background:#f4eee7;border-radius:18px;padding:20px;margin:22px 0"><div style="font-size:11px;color:#777">KODE LISENSI</div><div style="font-size:25px;font-weight:800;letter-spacing:.04em">${safe(licenseCode)}</div><div style="font-size:11px;color:#777;margin-top:14px">PIN</div><div style="font-size:25px;font-weight:800;letter-spacing:.08em">${safe(pin)}</div></div><p>Gunakan Kode Lisensi + PIN tersebut untuk masuk pertama kali. Setelah login, atur nama pasangan, tanggal wedding, budget, target tamu, dan foto wedding kalian.</p>`;
 return logOrderEmail(db,order.id,resend?"access_resent":"access_sent",order.customer_email,()=>sendMail({to:order.customer_email,subject,text:`Pembayaran berhasil. Order ${order.order_no}. Kode Lisensi: ${licenseCode}. PIN: ${pin}. Buka MenujuKita: ${APP_URL}/auth/sign-in`,html:mailShell("MenujuKita siap digunakan",body,{label:"Buka MenujuKita",url:`${APP_URL}/auth/sign-in`}),idempotencyKey:resend?`mk-${order.id}-access-resend-${Date.now()}`:`mk-${order.id}-access-${order.license_id||"new"}`}));
}
