-- MenujuKita commerce / order system
CREATE TABLE IF NOT EXISTS payment_methods(
  code text PRIMARY KEY,
  label text NOT NULL,
  type text NOT NULL CHECK(type IN('bank','ewallet','qris')),
  account_no text,
  account_name text,
  merchant_id text,
  instructions text,
  qr_image_path text,
  sort_order integer NOT NULL DEFAULT 0,
  is_active boolean NOT NULL DEFAULT true,
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS orders(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  public_token text NOT NULL UNIQUE,
  order_no text NOT NULL UNIQUE,
  customer_name text NOT NULL,
  customer_email text NOT NULL,
  customer_whatsapp text NOT NULL,
  couple_names text,
  wedding_date date,
  product text NOT NULL DEFAULT 'MenujuKita',
  amount numeric(14,2) NOT NULL DEFAULT 49000,
  payment_method_code text REFERENCES payment_methods(code),
  payment_snapshot jsonb NOT NULL DEFAULT '{}'::jsonb,
  status text NOT NULL DEFAULT 'pending_payment' CHECK(status IN('pending_payment','awaiting_verification','needs_confirmation','payment_rejected','payment_verified','access_sent','completed','cancelled')),
  claimed_at timestamptz,
  verified_at timestamptz,
  access_sent_at timestamptz,
  completed_at timestamptz,
  license_id uuid UNIQUE REFERENCES licenses(id) ON DELETE SET NULL,
  license_code text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS payment_claims(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  method_code text NOT NULL,
  claimed_at timestamptz NOT NULL DEFAULT now(),
  note text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS email_events(
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  order_id uuid REFERENCES orders(id) ON DELETE CASCADE,
  kind text NOT NULL,
  recipient text NOT NULL,
  status text NOT NULL CHECK(status IN('sent','failed')),
  provider_id text,
  error text,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS order_activity(
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id uuid NOT NULL REFERENCES orders(id) ON DELETE CASCADE,
  event text NOT NULL,
  metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status,created_at DESC);
CREATE INDEX IF NOT EXISTS idx_orders_customer_email ON orders(customer_email);
CREATE INDEX IF NOT EXISTS idx_order_activity_order_created ON order_activity(order_id,created_at);

INSERT INTO payment_methods(code,label,type,account_no,account_name,merchant_id,instructions,qr_image_path,sort_order,is_active) VALUES
('bri','BRI','bank','518301014886532','Muhammad Shadiq Muntashir',NULL,'Transfer sesuai total order ke rekening BRI ini.',NULL,1,true),
('mandiri','Mandiri','bank','1510018726163','Muhammad Shadiq',NULL,'Transfer sesuai total order ke rekening Mandiri ini.',NULL,2,true),
('bsi','BSI','bank','7273584344','Muhammad Shadiq Muntashir',NULL,'Transfer sesuai total order ke rekening Bank Syariah Indonesia ini.',NULL,3,true),
('bank-sulteng','Bank Sulteng','bank','0010201272944','Muhammad Shadiq Muntashir',NULL,'Transfer sesuai total order ke rekening Bank Sulteng ini.',NULL,4,true),
('gopay','GoPay','ewallet','082258687238','Muhammad Shadiq Muntashir',NULL,'Kirim sesuai total order ke nomor GoPay ini.',NULL,5,true),
('qris','QRIS','qris','ID1026601784022','TEMAN DIGITAL','ID1026601784022','Sebelum melakukan pembayaran, pastikan nama merchant yang muncul adalah TEMAN DIGITAL.','/qris-teman-digital.svg',6,true)
ON CONFLICT(code) DO NOTHING;
