-- MenujuKita license + PIN authentication migration.
-- Secret values are seeded privately after migration; no PIN value/hash is committed in this file.
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS admin_pin_hash text;
ALTER TABLE app_settings ADD COLUMN IF NOT EXISTS admin_pin_salt text;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS pin_hash text;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS pin_salt text;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS pin_hint text;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS last_login_at timestamptz;
ALTER TABLE licenses ADD COLUMN IF NOT EXISTS pin_updated_at timestamptz;
CREATE TABLE IF NOT EXISTS license_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),license_id uuid NOT NULL REFERENCES licenses(id) ON DELETE CASCADE,token_hash text NOT NULL UNIQUE,user_agent text,ip_hash text,created_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL DEFAULT(now()+interval '30 days'),revoked_at timestamptz);
CREATE INDEX IF NOT EXISTS idx_license_sessions_active ON license_sessions(license_id,expires_at) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS admin_sessions(id uuid PRIMARY KEY DEFAULT gen_random_uuid(),token_hash text NOT NULL UNIQUE,user_agent text,ip_hash text,created_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),expires_at timestamptz NOT NULL DEFAULT(now()+interval '12 hours'),revoked_at timestamptz);
CREATE INDEX IF NOT EXISTS idx_admin_sessions_active ON admin_sessions(expires_at) WHERE revoked_at IS NULL;
CREATE TABLE IF NOT EXISTS access_logs(id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,actor_type text NOT NULL CHECK(actor_type IN('license','admin','system')),license_id uuid REFERENCES licenses(id) ON DELETE SET NULL,event text NOT NULL,success boolean NOT NULL DEFAULT true,ip_hash text,user_agent text,metadata jsonb NOT NULL DEFAULT '{}'::jsonb,created_at timestamptz NOT NULL DEFAULT now());
CREATE INDEX IF NOT EXISTS idx_access_logs_created ON access_logs(created_at DESC);
CREATE INDEX IF NOT EXISTS idx_access_logs_license ON access_logs(license_id,created_at DESC);
