import { createHash, createHmac, timingSafeEqual } from 'node:crypto';

const BUCKET='menujukita-private';
const enc=v=>encodeURIComponent(String(v)).replace(/[!'()*]/g,c=>'%'+c.charCodeAt(0).toString(16).toUpperCase());
const sha256=v=>createHash('sha256').update(v).digest('hex');
const hmac=(key,value)=>createHmac('sha256',key).update(value).digest();
const safeEqual=(a,b)=>{const x=Buffer.from(String(a)),y=Buffer.from(String(b));return x.length===y.length&&timingSafeEqual(x,y)};

function awsConfig(){const accessKeyId=process.env.AWS_ACCESS_KEY_ID,secretAccessKey=process.env.AWS_SECRET_ACCESS_KEY,endpoint=process.env.AWS_ENDPOINT_URL_S3,region=process.env.AWS_REGION;if(!accessKeyId||!secretAccessKey||!endpoint||!region)throw new Error('storage_env_missing');return{accessKeyId,secretAccessKey,endpoint:new URL(endpoint),region}}
function amzDate(d=new Date()){const iso=d.toISOString().replace(/[:-]|\.\d{3}/g,'');return{full:iso,short:iso.slice(0,8)}}
function uri(key){return'/'+enc(BUCKET)+'/'+String(key).split('/').map(enc).join('/')}
function signingKey(secret,date,region){const kDate=hmac(Buffer.from('AWS4'+secret),date),kRegion=hmac(kDate,region),kService=hmac(kRegion,'s3');return hmac(kService,'aws4_request')}
function presign(method,key,expires=300){const{accessKeyId,secretAccessKey,endpoint,region}=awsConfig(),{full,short}=amzDate(),scope=`${short}/${region}/s3/aws4_request`,params={'X-Amz-Algorithm':'AWS4-HMAC-SHA256','X-Amz-Credential':`${accessKeyId}/${scope}`,'X-Amz-Date':full,'X-Amz-Expires':String(Math.max(30,Math.min(900,Number(expires)||300))),'X-Amz-SignedHeaders':'host'},query=Object.entries(params).sort(([a],[b])=>a.localeCompare(b)).map(([k,v])=>`${enc(k)}=${enc(v)}`).join('&'),path=uri(key),canonical=[method,path,query,`host:${endpoint.host}\n`,'host','UNSIGNED-PAYLOAD'].join('\n'),toSign=['AWS4-HMAC-SHA256',full,scope,sha256(canonical)].join('\n'),signature=createHmac('sha256',signingKey(secretAccessKey,short,region)).update(toSign).digest('hex');return`${endpoint.origin}${path}?${query}&X-Amz-Signature=${signature}`}
function auth(req){const secret=process.env.INTERNAL_SECRET||'',header=req.headers.get('authorization')||'';return secret.length>=32&&safeEqual(header,`Bearer ${secret}`)}
const json=(body,status=200)=>Response.json(body,{status,headers:{'cache-control':'no-store'}});

export default{async fetch(request){const url=new URL(request.url);if(request.method==='GET'&&(url.pathname==='/'||url.pathname==='/health'))return json({ok:true,storageEnv:Boolean(process.env.AWS_ACCESS_KEY_ID&&process.env.AWS_SECRET_ACCESS_KEY&&process.env.AWS_ENDPOINT_URL_S3&&process.env.AWS_REGION),database:Boolean(process.env.DATABASE_URL)});if(request.method!=='POST')return json({error:'method_not_allowed'},405);if(!auth(request))return json({error:'unauthorized'},401);const body=await request.json().catch(()=>null),op=String(body?.op||''),key=String(body?.key||'');if(!key||key.length>1024||key.includes('..'))return json({error:'invalid_key'},400);try{if(op==='presign-upload')return json({url:presign('PUT',key,300)});if(op==='presign-download')return json({url:presign('GET',key,120)});if(op==='head'){const res=await fetch(presign('HEAD',key,120),{method:'HEAD'});return json({ok:res.ok,status:res.status,size:Number(res.headers.get('content-length')||0)},res.ok?200:res.status)}if(op==='delete'){const res=await fetch(presign('DELETE',key,120),{method:'DELETE'});return json({ok:res.ok,status:res.status},res.ok?200:res.status)}return json({error:'unknown_op'},400)}catch(error){console.error('storagebridge_error',error instanceof Error?error.message:String(error));return json({error:'storage_bridge_error'},500)}}};
