import GuestImport from "@/components/live/guest-import";
import { LinkIcon,Plus } from "lucide-react";
import { addGuest,deleteGuest,updateGuest } from "@/app/app/actions";
import { signRsvpParty } from "@/lib/rsvp";
export default function GuestsSection({guests,wedding}:{guests:any[];wedding:any;canEdit:boolean}){
 const attending=guests.filter(g=>g.rsvp_status==="attending").reduce((s,g)=>s+Number(g.actual_pax||g.expected_pax||1),0),waiting=guests.filter(g=>["waiting","not_sent","maybe"].includes(g.rsvp_status)).length,declined=guests.filter(g=>g.rsvp_status==="not_attending").length;
 return <section id="guests" className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">GUESTS</span><h2 className="serif">Guest Book</h2><p>Daftar tamu yang terasa seperti address book, bukan spreadsheet.</p></div><div className="module-score"><b>{attending}</b><span>confirmed pax</span></div></header>
  <div className="guest-overview"><div><small>Target</small><b>{wedding.guest_target||0}</b></div><div><small>Attending</small><b>{attending}</b></div><div><small>Waiting</small><b>{waiting}</b></div><div><small>Declined</small><b>{declined}</b></div></div>
  <details className="composer-card"><summary><span><Plus size={18}/>Tambah tamu</span><small>Individu atau satu keluarga/party</small></summary><form action={addGuest} className="editor-form"><input className="input span-2" name="name" placeholder="Nama / keluarga" required/><input className="input" name="phone" placeholder="WhatsApp"/><input className="input" name="email" type="email" placeholder="Email (opsional)"/><select className="input" name="side" defaultValue="other"><option value="partner_one">Keluarga pasangan 1</option><option value="partner_two">Keluarga pasangan 2</option><option value="shared">Bersama</option><option value="other">Lainnya</option></select><input className="input" name="group_name" placeholder="Group, mis. Keluarga"/><input className="input span-2" name="max_pax" type="number" min="1" max="20" defaultValue="2"/><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah ke Guest Book</button></form></details>
  <div className="guest-book">{guests.length?guests.map(g=>{const sig=g.party_id?signRsvpParty(String(g.party_id)):null;return <details className="guest-contact-card" key={g.id}><summary><div className="guest-avatar">{String(g.name).slice(0,1).toUpperCase()}</div><div className="item-main"><b>{g.name}</b><span>{g.group_name||"Other"} · {g.phone||"tanpa nomor"}</span></div><div className="guest-status"><span className={"status-dot status-"+g.rsvp_status}>{g.rsvp_status}</span><b>{g.actual_pax??g.expected_pax??1} pax</b></div></summary><div className="item-editor">{sig&&<a className="rsvp-action" href={"/rsvp/"+g.party_id+"/"+sig} target="_blank"><LinkIcon size={14}/> Buka RSVP publik</a>}<form action={updateGuest} className="editor-form"><input type="hidden" name="id" value={g.id}/><input className="input span-2" name="name" defaultValue={g.name} required/><input className="input" name="phone" defaultValue={g.phone||""}/><input className="input" name="email" type="email" defaultValue={g.email||""}/><select className="input" name="side" defaultValue={g.side||"other"}><option value="partner_one">Keluarga pasangan 1</option><option value="partner_two">Keluarga pasangan 2</option><option value="shared">Bersama</option><option value="other">Lainnya</option></select><input className="input" name="group_name" defaultValue={g.group_name||"Other"}/><input className="input" name="expected_pax" type="number" min="1" max="20" defaultValue={Number(g.expected_pax||1)}/><input className="input" name="actual_pax" type="number" min="0" max="20" defaultValue={Number(g.actual_pax??g.expected_pax??1)}/><select className="input span-2" name="status" defaultValue={g.rsvp_status}><option value="not_sent">Not sent</option><option value="waiting">Waiting</option><option value="attending">Attending</option><option value="not_attending">Declined</option><option value="maybe">Maybe</option></select><input className="input span-2" name="dietary_note" defaultValue={g.dietary_note||""} placeholder="Dietary note"/><textarea className="input span-2" name="notes" defaultValue={g.notes||""}/><button className="btn btn-primary span-2">Simpan Tamu</button></form><form action={deleteGuest} className="danger-zone"><input type="hidden" name="id" value={g.id}/><button className="text-danger">Hapus tamu</button></form></div></details>}):<div className="calm-empty">Guest Book masih kosong.</div>}</div>
  <GuestImport/>
 </section>
}
