import { KeyRound,ShieldCheck,Smartphone,UsersRound } from "lucide-react";
import PartnerInvitePanel from "@/components/live/partner-invite-panel";
export default function MembersSection({members,role,partnerStatus,partnerName}:{members:any[];invites:any[];role:string;partnerStatus?:string|null;partnerName?:string|null}){
 return <section id="team" className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">TIM</span><h2 className="serif">Rencanakan bersama.</h2><p>Satu wedding dengan data bersama. Pasangan kedua dapat bergabung melalui undangan pribadi dan memakai PIN masing-masing.</p></div><UsersRound size={28}/></header>
  <div className="team-access-grid"><article className="team-access-card accent"><KeyRound size={23}/><div><small>AKSES UTAMA</small><h3>Kode Lisensi + PIN</h3><p>Tidak perlu akun email terpisah. Kode Lisensi tetap satu, tetapi PIN setiap pasangan berbeda.</p></div></article><article className="team-access-card"><Smartphone size={23}/><div><small>MULTI PERANGKAT</small><h3>HP & laptop pasangan</h3><p>Masuk dari perangkat lain dengan Kode Lisensi dan PIN pribadi. Sesi bisa diputus jika diperlukan.</p></div></article><article className="team-access-card"><ShieldCheck size={23}/><div><small>BANTUAN</small><h3>Bantuan admin</h3><p>Teman Digital dapat membantu workspace dari Control Center dan setiap akses support tercatat.</p></div></article></div>
  <PartnerInvitePanel role={role} status={partnerStatus} name={partnerName}/>
  <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>IDENTITAS WORKSPACE</small><h3>Catatan tim wedding</h3></div></div><div className="studio-list">{members.map(m=><div className="studio-item static-item" key={m.id}><div className="member-avatar">{String(m.display_name||"M").slice(0,1).toUpperCase()}</div><div className="item-main"><b>{m.display_name||"Wedding Owner"}</b><span>{m.role} · {m.can_view_budget?"akses dana penuh":"akses standar"}</span></div></div>)}</div></section>
 </section>
}
