import {Plus,WalletCards} from "lucide-react";
import {addBudgetItem,addPayment,deleteBudgetItem,deletePayment,updateBudgetItem,updateFunds,updatePayment} from "@/app/app/actions";
import {dateLabel,money,labels} from "./shared";
import CurrencyInput from "@/components/currency-input";
import ConfirmSubmit from "@/components/confirm-submit";
import FinanceLedgerSection from "@/components/live/finance-ledger-section";
import type {CashEntry,FinanceSummary} from "@/lib/finance";
const inputDate=(v:any)=>v?String(v).slice(0,10):"";
export default function MoneySection({wedding,metrics,budgetItems,payments,vendors,cashEntries,financeSummary}:{wedding:any;metrics:any;budgetItems:any[];payments:any[];vendors:any[];cashEntries:CashEntry[];financeSummary:FinanceSummary;canEdit:boolean}){
 return <section id="money" className="module-stack">
  <header className="module-editorial-head"><div><span className="micro-label">DANA</span><h2 className="serif">Wedding Wallet</h2><p>Budget yang mudah dibaca, komitmen yang terlihat, dan angka yang membantu keputusan.</p></div><WalletCards size={28}/></header>
  <FinanceLedgerSection entries={cashEntries} summary={financeSummary}/>
  <div className="wallet-hero"><div><small>SAFE TO SPEND</small><strong>{money(metrics.safeToSpend)}</strong><span>Dana yang masih aman setelah pembayaran, komitmen, dan buffer.</span></div><div className="wallet-metrics"><p><small>TOTAL BUDGET</small><b>{money(wedding.budget_total)}</b></p><p><small>TERBAYAR</small><b>{money(metrics.paid)}</b></p><p><small>TERKOMITMEN</small><b>{money(metrics.committed)}</b></p><p><small>BUFFER</small><b>{money(wedding.reserve_buffer)}</b></p></div></div>
  <details className="composer-card"><summary><span>Atur target anggaran dan cadangan</span><small>Anggaran adalah target biaya, bukan saldo tunai</small></summary><form action={updateFunds} className="editor-form money-funds-form"><label className="field"><span>Total Budget</span><CurrencyInput name="budget_total" defaultValue={Number(wedding.budget_total||0)}/></label><label className="field span-2"><span>Buffer yang Dijaga</span><CurrencyInput name="reserve_buffer" defaultValue={Number(wedding.reserve_buffer||0)}/></label><button className="btn btn-primary span-2">Simpan Dana</button></form></details>
  <div className="two-column-studio">
   <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>RENCANA BUDGET</small><h3>Alokasi</h3></div><span>{budgetItems.length} item</span></div>
    <details className="inline-composer"><summary><Plus size={16}/> Tambah alokasi</summary><form action={addBudgetItem} className="editor-form"><input className="input span-2" name="name" placeholder="Mis. Catering" required/><select className="input span-2" name="vendor_id" defaultValue=""><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><label className="field"><span>Rencana</span><CurrencyInput name="planned_amount"/></label><label className="field"><span>Aktual</span><CurrencyInput name="actual_amount"/></label><input className="input" name="due_date" type="date"/><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah</button></form></details>
    <div className="studio-list">{budgetItems.length?budgetItems.map(b=><details className="studio-item" key={b.id}><summary><div className="item-main"><b>{b.name}</b><span>{b.vendor_name||"Tanpa vendor"} · Catat pembayaran melalui Jadwal Pembayaran</span></div><strong>{money(b.actual_amount||b.planned_amount)}</strong></summary><div className="item-editor"><form action={updateBudgetItem} className="editor-form"><input type="hidden" name="id" value={b.id}/><input className="input span-2" name="name" defaultValue={b.name} required/><select className="input span-2" name="vendor_id" defaultValue={b.vendor_id||""}><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><label className="field"><span>Rencana</span><CurrencyInput name="planned_amount" defaultValue={Number(b.planned_amount||0)}/></label><label className="field"><span>Aktual</span><CurrencyInput name="actual_amount" defaultValue={Number(b.actual_amount||0)}/></label><input className="input" name="due_date" type="date" defaultValue={inputDate(b.due_date)}/><textarea className="input span-2" name="notes" defaultValue={b.notes||""}/><button className="btn btn-primary span-2">Simpan</button></form><form action={deleteBudgetItem} className="danger-zone"><input type="hidden" name="id" value={b.id}/><ConfirmSubmit message={"Hapus alokasi “"+b.name+"”?"}>Hapus alokasi</ConfirmSubmit></form></div></details>):<div className="calm-empty actionable"><b>Belum ada alokasi.</b><span>Mulai dari pos terbesar seperti venue atau catering.</span></div>}</div>
   </section>
   <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>PEMBAYARAN</small><h3>Jadwal pembayaran</h3></div>{metrics.overduePayments>0&&<span className="attention-chip">{metrics.overduePayments} terlambat</span>}</div>
    <details className="inline-composer"><summary><Plus size={16}/> Tambah pembayaran</summary><form action={addPayment} className="editor-form"><input className="input span-2" name="description" placeholder="Mis. DP Fotografer" required/><select className="input span-2" name="vendor_id" defaultValue=""><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className="input span-2" name="budget_item_id" defaultValue=""><option value="">Tidak terkait alokasi</option>{budgetItems.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label className="field"><span>Nominal</span><CurrencyInput name="amount" min={1} required/></label><input className="input" name="due_date" type="date"/><input className="input span-2" name="payment_method" placeholder="Metode pembayaran"/><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah pembayaran</button></form></details>
    <div className="studio-list">{payments.length?payments.map(p=><details className="studio-item" key={p.id}><summary><div className="item-main"><b>{p.description}</b><span>{p.vendor_name||"Tanpa vendor"} · {dateLabel(p.due_date)}</span></div><div className="item-right"><strong>{money(p.amount)}</strong><span className={"status-dot status-"+p.status}>{labels[p.status]||p.status}</span></div></summary><div className="item-editor"><form action={updatePayment} className="editor-form"><input type="hidden" name="id" value={p.id}/><input className="input span-2" name="description" defaultValue={p.description} required/><select className="input span-2" name="vendor_id" defaultValue={p.vendor_id||""}><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className="input span-2" name="budget_item_id" defaultValue={p.budget_item_id||""}><option value="">Tidak terkait alokasi</option>{budgetItems.map(b=><option key={b.id} value={b.id}>{b.name}</option>)}</select><label className="field"><span>Nominal</span><CurrencyInput name="amount" min={1} defaultValue={Number(p.amount)}/></label><input className="input" name="due_date" type="date" defaultValue={inputDate(p.due_date)}/><select className="input" name="status" defaultValue={p.status==="overdue"?"upcoming":p.status}><option value="upcoming">Akan datang</option><option value="paid">Lunas</option><option value="cancelled">Batal</option></select><input className="input" name="payment_method" defaultValue={p.payment_method||""} placeholder="Metode"/><textarea className="input span-2" name="notes" defaultValue={p.notes||""}/><button className="btn btn-primary span-2">Simpan</button></form><form action={deletePayment} className="danger-zone"><input type="hidden" name="id" value={p.id}/><ConfirmSubmit message={"Hapus pembayaran “"+p.description+"”?"}>Hapus pembayaran</ConfirmSubmit></form></div></details>):<div className="calm-empty actionable"><b>Belum ada jadwal pembayaran.</b><span>Tambahkan DP atau pelunasan vendor agar Safe to Spend tetap akurat.</span></div>}</div>
   </section>
  </div>
 </section>
}
