import { CalendarRange,Check,Clock3,Plus } from "lucide-react";
import { addTask,deleteTask,toggleTask,updateTask,addRundownItem,deleteRundownItem,updateRundownItem } from "@/app/app/actions";
import { dateLabel,timeLabel,labels } from "./shared";
const inputDate=(v:any)=>v?String(v).slice(0,10):"";
const inputDateTime=(v:any)=>v?new Date(v).toISOString().slice(0,16):"";
function phaseFor(task:any,weddingDate:any){
 if(String(task.category).toLowerCase().includes("day-h"))return"Day-H";
 if(!task.due_date||!weddingDate)return"Planning";
 const gap=Math.ceil((new Date(weddingDate).getTime()-new Date(task.due_date).getTime())/86400000);
 if(gap>180)return"Foundation";if(gap>90)return"Vendors";if(gap>45)return"Details";if(gap>21)return"Guests";return"Final Weeks";
}
export default function PlanSection({tasks,rundown,members,vendors,weddingDate}:{tasks:any[];rundown:any[];members:any[];vendors:any[];canEdit:boolean;weddingDate:any}){
 const phases=["Foundation","Vendors","Details","Guests","Final Weeks","Day-H"],done=tasks.filter(t=>t.status==="done").length;
 return <section id="plan" className="module-stack">
  <header className="module-editorial-head"><div><span className="micro-label">PLAN</span><h2 className="serif">Wedding Journey</h2><p>Fokus pada fase perjalanan, bukan tumpukan task tanpa konteks.</p></div><div className="module-score"><b>{done}/{tasks.length}</b><span>selesai</span></div></header>
  <div className="journey-phases">{phases.map(p=>{const count=tasks.filter(t=>phaseFor(t,weddingDate)===p).length,finished=tasks.filter(t=>phaseFor(t,weddingDate)===p&&t.status==="done").length;return <div className="journey-phase" key={p}><span>{p}</span><b>{finished}/{count}</b></div>})}</div>
  <details className="composer-card"><summary><span><Plus size={18}/>Tambah task</span><small>Buat hal baru yang perlu dibereskan</small></summary><form action={addTask} className="editor-form"><input className="input span-2" name="title" placeholder="Apa yang perlu dilakukan?" required/><textarea className="input span-2" name="description" placeholder="Catatan (opsional)"/><select className="input" name="category" defaultValue="general"><option value="general">General</option><option value="vendor">Vendor</option><option value="guest">Guest</option><option value="attire">Busana</option><option value="document">Dokumen</option><option value="money">Money</option><option value="Day-H">Day-H</option></select><input className="input" type="date" name="due_date"/><select className="input" name="priority" defaultValue="medium"><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><select className="input" name="assignee_member_id" defaultValue=""><option value="">Belum ada PIC</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name||"Wedding team"}</option>)}</select><button className="btn btn-primary span-2">Tambah ke Journey</button></form></details>

  <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>CHECKLIST</small><h3>Yang sedang dikerjakan</h3></div><CalendarRange size={19}/></div>
   <div className="studio-list">{tasks.length?tasks.map(t=><details className={"studio-item task-item "+(t.status==="done"?"is-done":"")} key={t.id}>
    <summary><form action={toggleTask}><input type="hidden" name="id" value={t.id}/><button className={"task-check "+(t.status==="done"?"checked":"")} aria-label="Selesaikan task">{t.status==="done"?<Check size={15}/>:null}</button></form><div className="item-main"><b>{t.title}</b><span>{phaseFor(t,weddingDate)} · {dateLabel(t.due_date)} · {t.priority}</span></div><span className={"status-dot status-"+t.status}>{labels[t.status]||t.status}</span></summary>
    <div className="item-editor"><form action={updateTask} className="editor-form"><input type="hidden" name="id" value={t.id}/><input className="input span-2" name="title" defaultValue={t.title} required/><textarea className="input span-2" name="description" defaultValue={t.description||""}/><select className="input" name="category" defaultValue={t.category}><option value="general">General</option><option value="vendor">Vendor</option><option value="guest">Guest</option><option value="attire">Busana</option><option value="document">Dokumen</option><option value="money">Money</option><option value="Day-H">Day-H</option></select><input className="input" name="due_date" type="date" defaultValue={inputDate(t.due_date)}/><select className="input" name="priority" defaultValue={t.priority}><option value="low">Low</option><option value="medium">Medium</option><option value="high">High</option><option value="critical">Critical</option></select><select className="input" name="status" defaultValue={t.status}><option value="todo">To do</option><option value="in_progress">Berjalan</option><option value="done">Selesai</option><option value="skipped">Lewati</option></select><select className="input span-2" name="assignee_member_id" defaultValue={t.assignee_member_id||""}><option value="">Belum ada PIC</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name||"Wedding team"}</option>)}</select><button className="btn btn-primary">Simpan</button></form><form action={deleteTask} className="danger-zone"><input type="hidden" name="id" value={t.id}/><button className="text-danger">Hapus task</button></form></div>
   </details>):<div className="calm-empty"><span>Belum ada task.</span></div>}</div>
  </section>

  <section className="studio-panel clean-list-panel"><div className="panel-heading"><div><small>DAY-H PREP</small><h3>Rundown</h3></div><Clock3 size={19}/></div>
   <details className="inline-composer"><summary><Plus size={16}/> Tambah agenda</summary><form action={addRundownItem} className="editor-form"><input className="input span-2" name="activity" placeholder="Nama agenda" required/><input className="input" type="datetime-local" name="starts_at" required/><input className="input" type="datetime-local" name="ends_at"/><input className="input span-2" name="location" placeholder="Lokasi"/><select className="input" name="pic_member_id" defaultValue=""><option value="">Tanpa PIC</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select><select className="input" name="vendor_id" defaultValue=""><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah agenda</button></form></details>
   <div className="studio-list">{rundown.length?rundown.map(r=><details className="studio-item" key={r.id}><summary><span className="time-badge">{timeLabel(r.starts_at)}</span><div className="item-main"><b>{r.activity}</b><span>{r.location||"Lokasi belum diisi"}{r.vendor_name?" · "+r.vendor_name:""}</span></div><span className={"status-dot status-"+r.status}>{labels[r.status]||r.status}</span></summary><div className="item-editor"><form action={updateRundownItem} className="editor-form"><input type="hidden" name="id" value={r.id}/><input className="input span-2" name="activity" defaultValue={r.activity} required/><input className="input" type="datetime-local" name="starts_at" defaultValue={inputDateTime(r.starts_at)} required/><input className="input" type="datetime-local" name="ends_at" defaultValue={inputDateTime(r.ends_at)}/><input className="input span-2" name="location" defaultValue={r.location||""}/><select className="input" name="pic_member_id" defaultValue={r.pic_member_id||""}><option value="">Tanpa PIC</option>{members.map(m=><option key={m.id} value={m.id}>{m.display_name}</option>)}</select><select className="input" name="vendor_id" defaultValue={r.vendor_id||""}><option value="">Tanpa vendor</option>{vendors.map(v=><option key={v.id} value={v.id}>{v.name}</option>)}</select><select className="input" name="status" defaultValue={r.status}><option value="upcoming">Upcoming</option><option value="ready">Ready</option><option value="in_progress">Berjalan</option><option value="done">Done</option><option value="delayed">Delayed</option><option value="cancelled">Batal</option></select><textarea className="input" name="notes" defaultValue={r.notes||""}/><button className="btn btn-primary span-2">Simpan agenda</button></form><form action={deleteRundownItem} className="danger-zone"><input type="hidden" name="id" value={r.id}/><button className="text-danger">Hapus agenda</button></form></div></details>):<div className="calm-empty">Belum ada rundown.</div>}</div>
  </section>
 </section>
}
