import { Armchair,Plus } from "lucide-react";
import { addSeatingTable,assignGuestToTable,deleteSeatingTable,removeSeatAssignment,updateSeatingTable } from "@/app/app/seating-actions";
import ConfirmSubmit from "@/components/confirm-submit";
export default function SeatingSection({tables,assignments,guests,events}:{tables:any[];assignments:any[];guests:any[];events:any[];canEdit:boolean}){
 const byTable=new Map<string,any[]>();assignments.forEach(a=>{const x=byTable.get(String(a.table_id))||[];x.push(a);byTable.set(String(a.table_id),x)});
 return <section id="seating" className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">SEATING</span><h2 className="serif">Susun meja dengan tenang.</h2><p>Susun meja secara visual dan pindahkan tamu tanpa spreadsheet rumit.</p></div><div className="module-score"><b>{tables.length}</b><span>meja</span></div></header>
  <details className="composer-card"><summary><span><Plus size={18}/>Tambah meja</span><small>Buat meja baru untuk salah satu event</small></summary><form action={addSeatingTable} className="editor-form"><input className="input span-2" name="name" placeholder="Mis. Meja Keluarga 01" required/><input className="input" name="capacity" type="number" min="1" max="100" defaultValue="10"/><select className="input" name="event_id" defaultValue=""><option value="">Umum</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button className="btn btn-primary span-2">Buat Meja</button></form></details>
  <div className="visual-seating-grid">{tables.length?tables.map(t=>{const items=byTable.get(String(t.id))||[],occupied=items.reduce((s,a)=>s+Number(a.seats||1),0),pct=Math.min(100,Math.round(occupied/Math.max(1,Number(t.capacity))*100));return <details className="visual-table" key={t.id}><summary><div className="table-orbit"><div><Armchair size={20}/><b>{occupied}/{t.capacity}</b></div><i style={{"--seat":pct} as any}/></div><div className="item-main"><small>{t.event_name||"Umum"}</small><b>{t.name}</b><span>{Number(t.capacity)-occupied} kursi tersisa</span></div></summary><div className="table-detail"><div className="seat-chips">{items.length?items.map(a=><form action={removeSeatAssignment} key={a.id}><input type="hidden" name="id" value={a.id}/><button title="Klik untuk keluarkan dari meja"><span>{a.guest_name}</span><small>{a.seats} kursi</small></button></form>):<span className="muted">Belum ada tamu.</span>}</div><form action={assignGuestToTable} className="seat-assist"><input type="hidden" name="table_id" value={t.id}/><select className="input" name="guest_id" required defaultValue=""><option value="" disabled>Pilih tamu...</option>{guests.filter(g=>g.rsvp_status!=="not_attending").map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select><input className="input" name="seats" type="number" min="1" max="20" defaultValue="1"/><button className="btn btn-primary">Tempatkan</button></form><form action={updateSeatingTable} className="editor-form compact-editor"><input type="hidden" name="id" value={t.id}/><input className="input" name="name" defaultValue={t.name}/><input className="input" name="capacity" type="number" min="1" max="100" defaultValue={Number(t.capacity)}/><select className="input span-2" name="event_id" defaultValue={t.event_id||""}><option value="">Umum</option>{events.map(e=><option key={e.id} value={e.id}>{e.name}</option>)}</select><button className="btn span-2">Simpan meja</button></form><form action={deleteSeatingTable} className="danger-zone"><input type="hidden" name="id" value={t.id}/><ConfirmSubmit message={"Hapus meja “"+t.name+"”?"}>Hapus meja</ConfirmSubmit></form></div></details>}):<div className="calm-empty">Belum ada meja. Mulai ketika guest list sudah cukup final.</div>}</div>
 </section>
}
