import {Plus} from "lucide-react";
import {addVendor,deleteVendor,updateVendor} from "@/app/app/actions";
import {money,labels} from "./shared";
import CurrencyInput from "@/components/currency-input";
import ConfirmSubmit from "@/components/confirm-submit";
export default function VendorsSection({vendors}:{vendors:any[];canEdit:boolean}){
 const booked=vendors.filter(v=>["booked","completed"].includes(v.status)).length;
 return <section id="vendors" className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">VENDOR</span><h2 className="serif">Wedding Partners</h2><p>Kontak, harga, status deal, dan langkah berikutnya dalam satu tempat.</p></div><div className="module-score"><b>{booked}/{vendors.length}</b><span>terkunci</span></div></header>
  <details className="composer-card"><summary><span><Plus size={18}/>Tambah vendor</span><small>Catat kandidat atau vendor yang sudah deal</small></summary><VendorForm/></details>
  <div className="vendor-studio-grid">{vendors.length?vendors.map(v=><details className="vendor-studio-card" key={v.id}><summary><div className="vendor-monogram">{String(v.name).slice(0,2).toUpperCase()}</div><div className="item-main"><small>{v.category}</small><b>{v.name}</b><span>{v.pic_name||v.whatsapp||"Kontak belum diisi"}</span></div><div className="vendor-price"><strong>{money(v.agreed_price||v.quoted_price)}</strong><span className={"status-dot status-"+v.status}>{labels[v.status]||v.status}</span></div></summary><div className="item-editor"><form action={updateVendor} className="editor-form"><input type="hidden" name="id" value={v.id}/><input className="input span-2" name="name" defaultValue={v.name} required/><input className="input" name="category" defaultValue={v.category} required/><input className="input" name="pic_name" defaultValue={v.pic_name||""} placeholder="PIC"/><input className="input" name="whatsapp" defaultValue={v.whatsapp||""} placeholder="WhatsApp"/><input className="input" name="instagram" defaultValue={v.instagram||""} placeholder="Instagram"/><label className="field"><span>Harga penawaran</span><CurrencyInput name="quoted_price" defaultValue={Number(v.quoted_price||0)}/></label><label className="field"><span>Harga deal</span><CurrencyInput name="agreed_price" defaultValue={Number(v.agreed_price||0)}/></label><select className="input span-2" name="status" defaultValue={v.status}><option value="searching">Mencari</option><option value="shortlisted">Shortlist</option><option value="contacted">Dihubungi</option><option value="negotiating">Negosiasi</option><option value="booked">Terkunci</option><option value="completed">Selesai</option><option value="cancelled">Batal</option></select><textarea className="input span-2" name="notes" defaultValue={v.notes||""} placeholder="Catatan"/><button className="btn btn-primary span-2">Simpan Vendor</button></form><form action={deleteVendor} className="danger-zone"><input type="hidden" name="id" value={v.id}/><ConfirmSubmit message={"Hapus vendor “"+v.name+"”?"}>Hapus vendor</ConfirmSubmit></form></div></details>):<div className="calm-empty actionable"><b>Belum ada vendor.</b><span>Tambahkan kandidat pertama untuk mulai membandingkan pilihan.</span></div>}</div>
 </section>
}
function VendorForm(){return <form action={addVendor} className="editor-form"><input className="input span-2" name="name" placeholder="Nama vendor" required/><input className="input" name="category" placeholder="Kategori" required/><input className="input" name="pic_name" placeholder="PIC"/><input className="input" name="whatsapp" placeholder="WhatsApp"/><input className="input" name="instagram" placeholder="Instagram"/><label className="field"><span>Harga penawaran</span><CurrencyInput name="quoted_price"/></label><label className="field"><span>Harga deal</span><CurrencyInput name="agreed_price"/></label><select className="input span-2" name="status" defaultValue="searching"><option value="searching">Mencari</option><option value="shortlisted">Shortlist</option><option value="contacted">Dihubungi</option><option value="negotiating">Negosiasi</option><option value="booked">Terkunci</option></select><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah Vendor</button></form>}
