import { Plus } from "lucide-react";
import { addVendor,deleteVendor,updateVendor } from "@/app/app/actions";
import { money,labels } from "./shared";
export default function VendorsSection({vendors}:{vendors:any[];canEdit:boolean}){
 const booked=vendors.filter(v=>["booked","completed"].includes(v.status)).length;
 return <section id="vendors" className="module-stack"><header className="module-editorial-head"><div><span className="micro-label">VENDORS</span><h2 className="serif">Wedding Partners</h2><p>Kontak, deal, status, dan next step tanpa terasa seperti inventory.</p></div><div className="module-score"><b>{booked}/{vendors.length}</b><span>secured</span></div></header>
  <details className="composer-card"><summary><span><Plus size={18}/>Tambah vendor</span><small>Catat kandidat atau vendor yang sudah deal</small></summary><VendorForm/></details>
  <div className="vendor-studio-grid">{vendors.length?vendors.map(v=><details className="vendor-studio-card" key={v.id}><summary><div className="vendor-monogram">{String(v.name).slice(0,2).toUpperCase()}</div><div className="item-main"><small>{v.category}</small><b>{v.name}</b><span>{v.pic_name||v.whatsapp||"Kontak belum diisi"}</span></div><div className="vendor-price"><strong>{money(v.agreed_price||v.quoted_price)}</strong><span className={"status-dot status-"+v.status}>{labels[v.status]||v.status}</span></div></summary><div className="item-editor"><form action={updateVendor} className="editor-form"><input type="hidden" name="id" value={v.id}/><input className="input span-2" name="name" defaultValue={v.name} required/><input className="input" name="category" defaultValue={v.category} required/><input className="input" name="pic_name" defaultValue={v.pic_name||""} placeholder="PIC"/><input className="input" name="whatsapp" defaultValue={v.whatsapp||""} placeholder="WhatsApp"/><input className="input" name="instagram" defaultValue={v.instagram||""} placeholder="Instagram"/><input className="input" name="quoted_price" type="number" min="0" defaultValue={Number(v.quoted_price||0)}/><input className="input" name="agreed_price" type="number" min="0" defaultValue={Number(v.agreed_price||0)}/><select className="input span-2" name="status" defaultValue={v.status}><option value="searching">Searching</option><option value="shortlisted">Shortlisted</option><option value="contacted">Contacted</option><option value="negotiating">Negotiating</option><option value="booked">Booked</option><option value="completed">Completed</option><option value="cancelled">Cancelled</option></select><textarea className="input span-2" name="notes" defaultValue={v.notes||""} placeholder="Catatan"/><button className="btn btn-primary span-2">Simpan Vendor</button></form><form action={deleteVendor} className="danger-zone"><input type="hidden" name="id" value={v.id}/><button className="text-danger">Hapus vendor</button></form></div></details>):<div className="calm-empty">Belum ada vendor.</div>}</div>
 </section>
}
function VendorForm(){return <form action={addVendor} className="editor-form"><input className="input span-2" name="name" placeholder="Nama vendor" required/><input className="input" name="category" placeholder="Kategori" required/><input className="input" name="pic_name" placeholder="PIC"/><input className="input" name="whatsapp" placeholder="WhatsApp"/><input className="input" name="instagram" placeholder="Instagram"/><input className="input" name="quoted_price" type="number" min="0" placeholder="Harga penawaran"/><input className="input" name="agreed_price" type="number" min="0" placeholder="Harga deal"/><select className="input span-2" name="status" defaultValue="searching"><option value="searching">Searching</option><option value="shortlisted">Shortlisted</option><option value="contacted">Contacted</option><option value="negotiating">Negotiating</option><option value="booked">Booked</option></select><textarea className="input span-2" name="notes" placeholder="Catatan"/><button className="btn btn-primary span-2">Tambah Vendor</button></form>}
